<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>DI.Vms.Api</RootNamespace>
    <AssemblyName>DI.Vms.Api</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DI.Vms.Application\DI.Vms.Application.csproj" />
    <ProjectReference Include="..\DI.Vms.Domain\DI.Vms.Domain.csproj" />
    <ProjectReference Include="..\DI.Vms.Infrastructure\DI.Vms.Infrastructure.csproj" />
  </ItemGroup>

</Project>
