# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ICASwiftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ICASwiftApp
 pod 'QKMRZParser', '~> 2.0.0'
 pod 'SwiftyTesseract', '~> 3.1.3'
end
