/* ==========================================================================
   VMS - the people a visitor can come to see
   Server UATWEB01, database VMS.

   GENERATED from db/AD Export 03_07_2026.xlsx by db/tools/generate_seed_people.py.
   Do not edit by hand: run the generator against the new export instead.

   725 people across 26 companies.

   Requires 003_add_people.sql. Re-runnable, and worth re-running: it inserts
   people who are new, refreshes the title and company of people already there,
   and re-resolves every DiEntityId - so running it again after adding entities
   links the people who could not be matched the first time.

   Run it with either of:
       sqlcmd -S UATWEB01 -E -i db\004_seed_people.sql
       - or open it in SSMS against VMS and execute.
   ========================================================================== */

USE VMS;
GO

SET NOCOUNT ON;

DECLARE @people TABLE
(
    DisplayName NVARCHAR(200) NOT NULL,
    Title       NVARCHAR(200) NULL,
    Email       NVARCHAR(256) NULL,
    CompanyName NVARCHAR(200) NULL
);

INSERT INTO @people (DisplayName, Title, Email, CompanyName) VALUES
(N'Senthil Kumar', N'Manager - Operations', N'senthil@techsource.ae', N'TechSource'),
(N'Cigith Plakkil', N'Sr. Systems Administrator', N'cigith@techsource.ae', N'TechSource'),
(N'Khalid Bin Kalban', N'Vice Chairman & CEO', N'kkalban@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mushtaq Masood', N'Chief Operating Officer (COO)', N'mushtaq@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Omar Al Mesmar', N'General Manager', N'omar@dipark.com', N'Dubai Investments Park'),
(N'Reghuraj Chandran', N'IT Support Engineer', N'reghuraj@techsource.ae', N'TechSource'),
(N'Shafeeque', N'System Administrator', N'Shafeeque@techsource.ae', N'TechSource'),
(N'Nayyar Jawaid', N'Manager - Business Applications', N'nayyar@techsource.ae', N'TechSource'),
(N'Aamir Suleman', N'Associate Director - ERP', N'aamir@techsource.ae', N'TechSource'),
(N'Hojoh K.G', N'Manager – Master Data Management', N'hojoh@techsource.ae', N'TechSource'),
(N'Bassem M. Ibrahim', N'Head of Projects - Real Estate platform', N'bassem@dipark.com', N'Dubai Investments Park'),
(N'Ammar AL Duwaikh', N'Deputy GM - Commercial', N'ammar@dipark.com', N'Dubai Investments Park'),
(N'Emma Kamau', N'Sr. Sales & Marketing Executive', N'emma@dipark.com', N'Dubai Investments Park'),
(N'Ghassan Radwan', N'Project Manager', N'ghassan@dipark.com', N'Dubai Investments Park'),
(N'Mais Hassouna', N'Assistant Manager -Tenant Relation', N'mais@dipark.com', N'Dubai Investments Park'),
(N'Monaliza Bobis', N'Engineering Secretary', N'Monaliza@dipark.com', N'Dubai Investments Park'),
(N'Nesma Medhat', N'Team Leader', N'nesma@dipark.com', N'Dubai Investments Park'),
(N'Saeed Bugaraah', N'Deputy GM - Operations', N'saeed@dipark.com', N'Dubai Investments Park'),
(N'Samah Zeid', N'Team Leader – Revenue Dpt', N'samah@dipark.com', N'Dubai Investments Park'),
(N'Sheeba Mathew', N'Executive assistant – GM’s Office', N'sheeba@dipark.com', N'Dubai Investments Park'),
(N'Shabbir Rangwala', N'Asistant Manager – Finance', N'shabbir@dipark.com', N'Dubai Investments Park'),
(N'Sami Ibrahim', N'Project Manager', N'sami@dipark.com', N'Dubai Investments Park'),
(N'Sherry Ann C. Dacuyan', N'Assistant – Commercial Dept', N'sherry@dipark.com', N'Dubai Investments Park'),
(N'Waheeb Y. Mohammed', N'Commercial Manager', N'waheeb@dipark.com', N'Dubai Investments Park'),
(N'Sreekumar Brahmanandan', N'Investments Director', N'skumar@di-industries.com', N'Dubai Investments Industries'),
(N'Abir Farouk', N'Office Manager', N'Abir@di-industries.com', N'Dubai Investments Industries'),
(N'Binu', N'Store Keeper', N'm.binu@ebsl.com', N'Emirates Building System'),
(N'Firass', N'Senior Projects Manager', N'f.salamah@ebsl.com', N'Emirates Building System'),
(N'Joseph Chidiac', N'General Manager', N'j.chidiac@ebsl.com', N'Emirates Building System'),
(N'Haris', N'HR Generalist', N'h.kutty@ebsl.com', N'Emirates Building System'),
(N'Jishore Varghese', N'Project Coordinator', N'v.jishore@ebsl.com', N'Emirates Building System'),
(N'Kurian Simon', N'Sr.Accountant', N's.kurian@ebsl.com', N'Emirates Building System'),
(N'Manoj P John', N'Procurement Executive', N'm.john@ebsl.com', N'Emirates Building System'),
(N'Michael R. Sendon', N'Project Engineer', N's.mike@ebsl.com', N'Emirates Building System'),
(N'Mitri Matta', N'DGM', N'm.matta@ebsl.com', N'Emirates Building System'),
(N'Poonam', N'Executive Secretary', N'p.veervani@ebsl.com', N'Emirates Building System'),
(N'Riju', N'Production Control Supervisor', N'r.riju@ebsl.com', N'Emirates Building System'),
(N'Raghuram', N'QA/QC Engineer', N'n.raghu@ebsl.com', N'Emirates Building System'),
(N'Sameer Ahmed', N'Sales Manager - Dubai', N'a.sameer@ebsl.com', N'Emirates Building System'),
(N'Ahmad Saeed Bin Huwaidi Al Falasi', N'Group Public Relations Manager', N'asalhuwaidi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Abdul Basith Lowna', N'Accounts Manager', N'ablowna@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Alaa El Din Mohammed', N'Sr. Officer - Government Affairs', N'alaaeldin@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Danah Abbas', N'Public Relations Administrator', N'dana@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Cynthia Preethi Quadros', N'Manager – Marketing', N'cynthia@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Eman Lutfi Rabie', N'Manager - Shares', N'eman@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Hilda Fernandes', N'Executive Secretary', N'hilda@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Najat Kassir', N'Director - Group Marketing & Communications', N'najat@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ratika Singh', N'Manager – Sustainability', N'ratika.singh@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Taha Muallim', N'Assistant Manager – Finance', N'taha@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Saderuddin Panakkat', N'Chief Internal Audit Officer', N'saderuddin@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Suhail Majeed', N'Senior PR Administrator', N'suhail@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Lavina Pereira', N'Assistant Manager – IA Operations', N'lavina@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Obaid Al Salami', N'General Manager', N'alsalami@dirc.ae', N'Dubai Investment Realestate'),
(N'Yaqoob Lootah', N'Deputy General Manager', N'yaqoob@dirc.ae', N'Dubai Investment Realestate'),
(N'Tarek Mohamed', N'Associate Sales Director', N'tarek@dirc.ae', N'Dubai Investment Realestate'),
(N'Varghese Joseph', N'Supply Chain Analyst', N'varghese@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Abdulaziz AlSerkal', N'CEO Glass LLC', N'aserkal@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Muhammad Ayaz', N'Accounts Manager', N'ayazk@masharie.com', N'Masharie'),
(N'Felix', N'Sr. Detailer', N'felix@ebsl.com', N'Emirates Building System'),
(N'Ravi', N'Sr. Checker', N'ravi@ebsl.com', N'Emirates Building System'),
(N'Cedric', N'Detailer', N'cedric@ebsl.com', N'Emirates Building System'),
(N'Karunakaran', N'QA/QC – Document Controller', N'karunan.qc@ebsl.com', N'Emirates Building System'),
(N'Renjan Thomas', N'Quantitative survivor', N'renjan@domain.local', N'Emirates Building System'),
(N'Aswin Raj', N'Checker', N'aswin@ebsl.com', N'Emirates Building System'),
(N'Erwin Theodore', N'Accounts Clerk', N'erwin.t@ebsl.com', N'Emirates Building System'),
(N'Anilkumar Appupillai', N'Logistics Officer', N'a.anil@ebsl.com', N'Emirates Building System'),
(N'Anthuvan', N'Sr. Detailer', N'anthuvan@ebsl.com', N'Emirates Building System'),
(N'Abdullah', N'Sr. PR Officer', N'a.abdullah@ebsl.com', N'Emirates Building System'),
(N'Faizal Maliyakkal', N'Project Cum Procurement Officer', N'Faizal.Maliyakkal@dipark.com', N'Dubai Investments Park'),
(N'Mohamed Hassan El Sheikh', N'Sr. Revenue Executive', N'elsheikh@dipark.com', N'Dubai Investments Park'),
(N'Choukri Fares Massoud', N'Sr. Landscaping Engineer', N'chmassoud@dipark.com', N'Dubai Investments Park'),
(N'Hany El Nekity', N'Senior Legal Adviser', N'hany@dipark.com', N'Dubai Investments Park'),
(N'Muhammed Jalaludheen', N'IT Support Assistant', N'jalal@techsource.ae', N'TechSource'),
(N'Asma Mohamed Ahmad', N'Chief Human Resources & Administration Officer', N'a.mesmar@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohammad Salameh', N'Sr. Projects Manager', N'm.salameh@ebsl.com', N'Emirates Building System'),
(N'Sreejith K.', N'Procurement Assistant', N'k.sreejith@ebsl.com', N'Emirates Building System'),
(N'Mahendran', N'Sr. Detailer', N'b.mahendran@ebsl.com', N'Emirates Building System'),
(N'Ahmed Al Hamlawi', N'Technical & Design Head', N'ahmed@dirc.ae', N'Dubai Investment Realestate'),
(N'Sahira Barangai', N'Sr. Administration Officer', N'sahira@dirc.ae', N'Dubai Investment Realestate'),
(N'Nizar Mon Kadakkadan', N'Assistant Manager - Account', N'nizar@dirc.ae', N'Dubai Investment Realestate'),
(N'Kamal Sayed Ibrahim', N'Sr. Property Executive', N'kamal@dirc.ae', N'Dubai Investment Realestate'),
(N'Elshafia Mohamed Awad', N'Sr. Property Executive', N'elshafia@dirc.ae', N'Dubai Investment Realestate'),
(N'Fouad Hassan', N'Property Supervisor', N'fouad@dirc.ae', N'Dubai Investment Realestate'),
(N'Rabab El Dessouky', N'Director - Group HR', N'Rabab@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Arun Hissaria', N'Associate Director – Internal Audit', N'arun@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Amro Hammad', N'Senior Property Manager', N'Amro@dirc.ae', N'Dubai Investment Realestate'),
(N'Mansoor Alserkal', N'General Manager', N'mansoor@almujama.com', N'Al Mujama Real Estate'),
(N'Sahaya Bruno', N'Production Manager', N'Sahaya@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Ayman Ibrahim Awad', N'Sr. Security Manager', N'Aymanritaj@dirc.ae', N'Dubai Investment Realestate'),
(N'Barun Limbu', N'Property Executive', N'Barun@dirc.ae', N'Dubai Investment Realestate'),
(N'Hidayathulla Zakaria', N'Chief Accountant', N'Hidayath@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Junic Salvador', N'Designer', N'Junic@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Michael M.Consul', N'Supply Chain Manager', N'Michael@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Mohammed Shafi', N'Store Keeper', N'M.Shafi@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Moutasim Abuel Gasim', N'Finance Manager', N'Moutasim@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Jason D’cunha', N'Procurement Officer', N'jaisa.d@ebsl.com', N'Emirates Building System'),
(N'Domini Varghese', N'Admin Clerk', N'v.domini@ebsl.com', N'Emirates Building System'),
(N'Sameer Vannantavida', N'QC/QA Supervisor', N'sameer.qc@ebsl.com', N'Emirates Building System'),
(N'Pradeep', N'Sr Design & Estimation Engineer', N'Pradeep.d@ebsl.com', N'Emirates Building System'),
(N'Kishore Kumar Patil', N'Design & Estimation Manager', N'k.kishor@ebsl.com', N'Emirates Building System'),
(N'Rasool Ur Rehman', N'Site Inspector', N'Rehman@dipark.com', N'Dubai Investments Park'),
(N'Jamila Busamah', N'Sr. Revenue Executive', N'jamila.b@dipark.com', N'Dubai Investments Park'),
(N'Mohammed Saeed Al Raqbani', N'General Manager', N'mraqbani@di-industries.com', N'Dubai Investments Industries'),
(N'Hala Sadeq', N'Assistant Manager-HR', N'hala.s@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Yasmine Al Sharkawi', N'Sr. Executive Assistant & Facility Officer', N'yasmine@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohamed ElSahwi', N'Head of Compliance', N'mohamed.elsahwi@dubaiinvestments.com', N''),
(N'Samar Fayek', N'Administration Officer', N'samar@dipark.com', N'Dubai Investments Park'),
(N'K.Vandhiya Thevan', N'Detailer', N'vandhiya@ebsl.com', N'Emirates Building System'),
(N'Bobby Capiz Sabio', N'Fabrication Supervisor', N'c.bobby@ebsl.com', N'Emirates Building System'),
(N'Bikash Rai', N'Office Clerk', N'bikash@dirc.ae', N'Dubai Investment Realestate'),
(N'Mahmoud Ibrahim Al Shafi', N'Assistant Manager Landscape', N'mahmoud.ibrahim@dirc.ae', N'Dubai Investment Realestate'),
(N'Hazem Tarek Abbara', N'Gym Supervisor', N'hazem@dirc.ae', N'Dubai Investment Realestate'),
(N'Shireen Ateia', N'Manager – Group Human Resources', N'Shireen@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Aravindraj Perumal', N'Detailer', N'aravindraj@ebsl.com', N'Emirates Building System'),
(N'Ahmed Al Shared', N'Head of Operations', N'a.alsharid@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Durairaj Sekar', N'Detailer', N'durairaj@ebsl.com', N'Emirates Building System'),
(N'Ronaldo Cabalo', N'Administration Officer', N'ronaldo@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Irene', N'Secretary', N'Irene@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Alauddin Abdul', N'Maintenance', N'maintenance@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Sales Marketing', N'Sales Coordinator', N'salesmarketing@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Ramakrishnan Raghavan', N'Quality', N'quality@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Saju (Dispatch)', N'Dispatcher', N'Dispatch@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Jeremy Tandiama', N'Secretary cum AutoCAD Officer', N'Jeremy@dipark.com', N'Dubai Investments Park'),
(N'Lync Test for Microsoft', N'Testing Administrator', N'lynctest@techsource.ae', N''),
(N'J.Divakar', N'Checker', N'divakar@ebsl.com', N'Emirates Building System'),
(N'Nasser Al Meri', N'Sr. Tenant Relation Executive', N'nasser.almeri@dipark.com', N'Dubai Investments Park'),
(N'Saleh Omran', N'Senior Accountant', N'saleh@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Khalid A. Al Daboos', N'Sr. Manager - Portfolio Management', N'Kaldaboos@domain.local', N'Dubai Investments Industries'),
(N'Imtiyaz Hussain', N'Senior Accountant', N'imtiyaz@dipark.com', N'Dubai Investments Park'),
(N'Arunava Das', N'Design & Estimation Engineer', N'a.das@ebsl.com', N'Emirates Building System'),
(N'Manu Jose', N'Sr Design & Estimation Engineer', N'manu@ebsl.com', N'Emirates Building System'),
(N'Nishar', N'Sales Manager', N'nishar@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Production GMC', N'Production In charge', N'production@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Sameer Punnavila', N'Senior Accountant', N'sameer@propertiesinvestment.com', N'Properties Investment'),
(N'Muhammad Bilal', N'Accountant', N'muhammad.bilal@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Sandeep Singh', N'Site Supervisor', N'sandeep@dipark.com', N'Dubai Investments Park'),
(N'Magesh Dorairaj', N'Planner', N'planning@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Mohamed Youssef', N'Sr. Property Executive', N'youssef@propertiesinvestment.com', N'Properties Investment'),
(N'Mohammed Al Massri', N'Team Lead – IT Support', N'mohd.k@techsource.ae', N'TechSource'),
(N'Jayanti Maheshwari', N'Senior Manager - Internal Audit', N'jayanti@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohamed Hanon', N'Business Center Executive', N'Mohamed.Hanon@dipark.com', N'Dubai Investments Park'),
(N'Amar Hashim', N'Office Administrator-Ritaj', N'customerservice.amar@dirc.ae', N'Dubai Investment Realestate'),
(N'Jessica Corazon Tapoc', N'Assistant Finance Manager', N'jessica@dipark.com', N'Dubai Investments Park'),
(N'Mohammed Salah', N'Assistant Manager - IT', N'm.salah@emiratesglass.com', N'Emirates Glass'),
(N'Abdullah Abbas', N'Optimization Assistant', N'abdulla@emiratesglass.com', N'Emirates Glass'),
(N'Info EGL', N'info', N'info@emiratesglass.com', N'Emirates Glass'),
(N'Anish', N'Supervisor Flat Lamination', N'anish@emiratesglass.com', N'Emirates Glass'),
(N'edelmeirc', N'Technical Designer', N'edelmeirc@emiratesglass.com', N'Emirates Glass'),
(N'Mujeeb Malik', N'Invoicing Clerk', N'mujeeb@emiratesglass.com', N'Emirates Glass'),
(N'shiju', N'HSE Assistant', N'shiju@emiratesglass.com', N'Emirates Glass'),
(N'Suresh Babu', N'Assistant Manager - Production', N'sureshbabu@emiratesglass.com', N'Emirates Glass'),
(N'Jiju Keralodayam', N'Senior Supervisor - Health & Safety', N'jiju@emiratesglass.com', N'Emirates Glass'),
(N'Radha krishnan', N'Chief Accountant', N'radha@emiratesglass.com', N'Emirates Glass'),
(N'Aju Pappachan', N'QC Inspector', N'aju@domain.local', N'Emirates Glass'),
(N'Lalaine Trinidad', N'Estimation', N'lalaine@emiratesglass.com', N'Emirates Glass'),
(N'Kundukulam Francis John', N'Customer Service - Co-ordinator', N'john@emiratesglass.com', N'Emirates Glass'),
(N'M. Mahesh', N'Senior Optimizer', N'mahesh@emiratesglass.com', N'Emirates Glass'),
(N'Nasser Al Safadi', N'Debit Controller Executive', N'nasser@emiratesglass.com', N'Emirates Glass'),
(N'Neeraj Amal', N'Senior Workorder Executive', N'neeraj@emiratesglass.com', N'Emirates Glass'),
(N'Rajesh Sethi', N'Customer Service', N'rajesh@emiratesglass.com', N'Emirates Glass'),
(N'Sandeep Nair', N'Vice President - Operations', N'sandeep@emiratesglass.com', N'Emirates Glass'),
(N'Masoud Morshedy', N'PRO/Service Manager', N'masoud@emiratesglass.com', N'Emirates Glass'),
(N'Rodellito San Jose', N'Manager-Planning&Optimization', N'rodel@emiratesglass.com', N'Emirates Glass'),
(N'Umer Jamil', N'Assistant Manager - Finance', N'umer@emiratesglass.com', N'Emirates Glass'),
(N'Rumana Ahmad', N'Executive Secretary', N'rumana@emiratesglass.com', N'Emirates Glass'),
(N'Rizwan EGL', N'Executive President', N'rizwank@emiratesglass.com', N'Emirates Glass'),
(N'Mohammed Irshad', N'Logistics Coordinator', N'irshad@emiratesglass.com', N'Emirates Glass'),
(N'Hari Nandukkandy', N'Senior Manager -Sales', N'hari@emiratesglass.com', N'Emirates Glass'),
(N'Moez El Ashkar', N'Sales Manager', N'moez@emiratesglass.com', N'Emirates Glass'),
(N'Samih Yehia', N'Senior Vice president Sales & Marketing', N'samih@emiratesglass.com', N'Emirates Glass'),
(N'Rizwanulla khan', N'Executive President', N'rizwankhan@emiratesglass.com', N'Emirates Glass'),
(N'Amin Jouini', N'Mall Manager', N'amin@dirc.ae', N'Dubai Investment Realestate'),
(N'Sathish Vijayan', N'Sales Manager', N'sathish.v@ebsl.com', N'Emirates Building System'),
(N'Amit Gulati', N'Senior Supervisor - Production & Planning', N'amit@emiratesglass.com', N'Emirates Glass'),
(N'Anoop Ramaiah', N'Senior Dispatch Supervisor', N'AnoopRamaiah@emiratesglass.com', N'Emirates Glass'),
(N'Fathaulla Saheb - GlassLLC', N'CFO-Industrial Platform', N'', N'Emirates Glass'),
(N'Sarfaraz Asghar Ali', N'Manager Sales - BRG', N'Sarfaraz.a@emiratesglass.com', N'Emirates Glass'),
(N'Srijith P', N'Sales Manager', N'Srijith@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Julia Hapon - Palisades', N'Assistant Manager - Sales', N'julia@Palisades.ae', N'Palisades'),
(N'Sajid Imtiyaz', N'Logistics Coordinator', N'Sajid@emiratesglass.com', N'Emirates Glass'),
(N'Jover P Alcaraz', N'Projects Engineer', N'j.alcaraz@ebsl.com', N'Emirates Building System'),
(N'Veena Jajani', N'Document Controller', N'veena@emiratesglass.com', N'Emirates Glass'),
(N'Ramil Gacoscos', N'Estimator', N'ramil@emiratesglass.com', N'Emirates Glass'),
(N'Hitendra Kumar', N'Site Inspector cum Electrician', N'hitendra@dipark.com', N'Dubai Investments Park'),
(N'Vijaya Kumar', N'Tekla Detailer', N'vkumar@ebsl.com', N'Emirates Building System'),
(N'John Mohammed', N'Sales Representative', N'john.mohammed@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Basheer MPM', N'Accountant', N'basheer@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Amira El Asuoty', N'Senior Manager – VC/CEO Office', N'Amira@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Naqibullah Khan', N'Site Inspector', N'naqibullah@dipark.com', N'Dubai Investments Park'),
(N'James A.P', N'Finance Manager', N'james@litetechind.com', N'Lite-Tech Industries'),
(N'Nisath Ahamed Amanullah', N'Admin Assistant', N'nisath@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Muhammad Taqi', N'Finance Manager', N'mutaqi@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Rizwan Ali Rana', N'Site Inspector', N'rizwan@dipark.com', N'Dubai Investments Park'),
(N'Raju Saravanan', N'Sr. Systems & Products Dev. Specialist', N'r.saravanan@ebsl.com', N'Emirates Building System'),
(N'Ruth Ria Gonzales', N'Executive Assistant & Project Officer', N'ruth@techsource.ae', N'TechSource'),
(N'Vinay Musale', N'Sr. Design & Estimation Engineer', N'vinay.musale@ebsl.com', N'Emirates Building System'),
(N'EGL Maintenance', N'EGL- Maintenance', N'egl-Maintenance@emiratesglass.com', N'Emirates Glass'),
(N'Suresh Kumar', N'Maintenance Manager', N'sureshkumar@emiratesglass.com', N'Emirates Glass'),
(N'Nishant Shah', N'Chief Financial Officer', N'nishant@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Padma Venu', N'Assistant Manager - PR & Media', N'padma.venu@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Jitendra Purushottam Darji', N'Vat Accountant', N'Jitendra@dirc.ae', N'Dubai Investment Realestate'),
(N'Muhammad Frasat', N'Asst Accountant', N'frasat@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Mohammad Talha', N'Maintenance Engineer', N'Talha@emiratesglass.com', N'Emirates Glass'),
(N'Mahmoud Mohamed Ymany Temmy', N'Property Executive', N'mahmoud.ymany@dirc.ae', N'Dubai Investment Realestate'),
(N'Leo Acailar Escalante', N'Machine Operator', N'leo.c@ebsl.com', N'Emirates Building System'),
(N'Rey Casanova Edillo', N'Computer Operator', N'rey@ebsl.com', N'Emirates Building System'),
(N'Jovito Dicdican Maca-Ambac Jr', N'IT Technical Support', N'jovito@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'EBS Africa', N'Sales & Marketing Africa', N'ebsafrica@ebsl.com', N'Emirates Building System'),
(N'Mudassar Haffiz', N'Assistant Manager Finance', N'm.haffiz@ebsl.com', N'Emirates Building System'),
(N'Mubashir Hassan', N'Assistant Sales Manager', N'mubashir@dirc.ae', N'Dubai Investment Realestate'),
(N'Syed Mubarak', N'Manager - Estimation', N's.mubarak@emiratesglass.com', N'Emirates Glass'),
(N'DIP Reception', N'Receptionist', N'reception@dipark.com', N'Dubai Investments Park'),
(N'Ciril Davis', N'Procurement Executive', N'', N'Emirates Glass'),
(N'Musaed Al Haj - Masharie', N'Sr. Operations Manager', N'musaed@masharie.com', N'Masharie'),
(N'Amal Najahi', N'Relationship Manager', N'amal@dirc.ae', N'Dubai Investment Realestate'),
(N'Suhib Muneer Al Quran', N'Government Affairs', N'Suhib@dirc.ae', N'Dubai Investment Realestate'),
(N'Jaqueline Naranjo', N'Admin Officer', N'Jaqueline@dirc.ae', N'Dubai Investment Realestate'),
(N'CampBoss', N'Campboss', N'campboss@ebsl.com', N'Emirates Building System'),
(N'Salim Al Hajeri', N'Special Projects – Sr. Manager', N'salim@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Davis Johnson', N'Sales Representative', N'Davis@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'LGI Maintenance', N'LGI - Maintenance', N'lgi-Maintenance@emiratesglass.com', N'Emirates Glass'),
(N'Dhanu Thappa', N'Store Keeper', N'dhanu@ebsl.com', N'Emirates Building System'),
(N'Rume Odjadjare', N'Area Sales Manager (Ivory Coast & Ghana)', N'rume@ebsl.com', N'Emirates Building System'),
(N'Daniel Pascua', N'Production Supervisor', N'daniel.p@ebsl.com', N'Emirates Building System'),
(N'Franky Baptist', N'Accountant - AP', N'Franky@emiratesglass.com', N'Emirates Glass'),
(N'Julia Hapon', N'Sr. Sales and Leasing Executive', N'julia.h@dipark.com', N'Dubai Investments Park'),
(N'Stephan Felix Dias', N'Site Supervisor', N'stephan@dipark.com', N'Dubai Investments Park'),
(N'Mohammed Afsar Thotan', N'Accountant - AR & Banking', N'afsar.thotan@emiratesglass.com', N'Emirates Glass'),
(N'Rohail Sattar', N'Site/Erection Supervisor', N'Rohail.S@ebsl.com', N'Emirates Building System'),
(N'Abdulazeez Kallayi', N'Lead Developer', N'azeez@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Muhammad Imran', N'Leasing Consultant', N'Muhammad.imran@altaifbc.com', N'Al Taif Investment'),
(N'Beverley Theresa', N'Sr. OA Manager', N'beverley@domain.local', N'Mujama'),
(N'Rafi Masil Khan', N'HR & Admin', N'rafi@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Fatma Mualemi', N'Legal Advisor', N'fatma.mualemi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Venkat Raman', N'NDT Inspector', N'venkat_qc@ebsl.com', N'Emirates Building System'),
(N'Ajay Kushwah', N'Production Supervisor', N'ajay@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Manoj Kumar M', N'Sr. Shipping Supervisor', N'manojkumar@ebsl.com', N'Emirates Building System'),
(N'Jawad Bou Saab', N'Technical Facility Manager .', N'jawad@almujama.com', N'Al Mujama Real Estate'),
(N'Fawad Shah Sawar', N'Information Security Manager', N'fawad@techsource.ae', N'TechSource'),
(N'Anuraj Pushparajan', N'Industrial Engineer', N'anuraj@ebsl.com', N'Emirates Building System'),
(N'Manoj Kumar Pallathoor', N'Sr. Network Security Engineer', N'manoj.kumar@techsource.ae', N'TechSource'),
(N'Ahmed Ismail', N'Compliance Supervisor', N'ahmed.ismail@almujama.com', N'Al Mujama Real Estate'),
(N'Rizwan Sarwar', N'Sr. Credit Controller', N'rizwan.s@ebsl.com', N'Emirates Building System'),
(N'Hesham Ahmed', N'Assistant Vice President', N'', N'Al Mal Capital'),
(N'Mohammed Imran', N'Accountant', N'imran.k@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Ericson Ilustre', N'Computer Operator', N'ericson@ebsl.com', N'Emirates Building System'),
(N'Mani Arumugam', N'Production Supervisor', N'mani@litetechind.com', N'Lite-Tech Industries'),
(N'QC Department', N'Quality Controller', N'qc@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Hussain Makawi', N'PR Administrator', N'hussain.makawi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Marinel Labayo', N'Sr. Administrative Officer', N'marinellabayo@dirc.ae', N'Dubai Investment Realestate'),
(N'Shaju Varghese', N'Senior Finance Manager', N'shaju.v@ebsl.com', N'Emirates Building System'),
(N'Mohammed Azhar', N'Senior Planner', N'', N''),
(N'Mohamed Hanief Allawdeen', N'Senior Accountant', N'm.hanief@ebsl.com', N'Emirates Building System'),
(N'Hala EL Bizri', N'Executive Secretary to the CEO - Glass LLC', N'hala.bizri@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mahanas Nidiyandi', N'Network & Security Engineer', N'mahanas@techsource.ae', N'TechSource'),
(N'Libreng Cayabyab Galvan', N'Store Keeper', N'libreng@ebsl.com', N'Emirates Building System'),
(N'Piyush Jhanwar', N'Senior Finance Manager', N'piyush.jhanwar@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Susan Saad Elias', N'Relationship Manager', N'SusanSaad@dirc.ae', N'Dubai Investment Realestate'),
(N'Sultan Mahmoud Sultan', N'Project Manager', N'sultannafa@dirc.ae', N'Dubai Investment Realestate'),
(N'Leslie Anne Rayo', N'Document Controller', N'leslie@dirc.ae', N'Dubai Investment Realestate'),
(N'Mohammad Mehtab Mahfooz', N'Purchase officer', N'mehtab.m@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Afra Khalifa Al Suwaidi', N'Leasing Manager', N'afra@dirc.ae', N'Dubai Investment Realestate'),
(N'Hadia Misto', N'Retail Coordinator', N'hadia@propertiesinvestment.com', N'Properties Investment'),
(N'Alex Vibin', N'ERP Project Manager', N'alex@masharie.com', N'Masharie'),
(N'Mohamed Abdul Hasan', N'Logistic Coordinator', N'Mohamed.Hasan@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Mirdif Sales', N'Sales Executive', N'', N'Mirdif Hills'),
(N'Karim Mohamed', N'Sr. Property Executive', N'karim.mohamed@dirc.ae', N'Dubai Investment Realestate'),
(N'Zubair Khan', N'Accounts Manager', N'zubair@dirc.ae', N'Dubai Investment Realestate'),
(N'Rami Ibrahim', N'Facility Engineer', N'ramitabarni@dirc.ae', N'Dubai Investment Realestate'),
(N'Majd Talas', N'Sr. Accountant', N'majdtalas@dirc.ae', N'Dubai Investment Realestate'),
(N'Binu Raveendran', N'Procurement Manager', N'binu.r@ebsl.com', N'Emirates Building System'),
(N'EBS Ethiopia', N'Sales & Marketing Ethiopia', N'ebsethiopia@ebsl.com', N'Emirates Building System'),
(N'Ola Ezzelddin', N'Legal secretary', N'ola.ezzelddin@dipark.com', N'Dubai Investments Park'),
(N'Jithesh Kesavan', N'Supervisor - Production', N'Jithesh.k@emiratesglass.com', N'Emirates Glass'),
(N'Pankaj Raju', N'Procurement Supervisor', N'pankaj@emiratesglass.com', N'Emirates Glass'),
(N'Silvi El Saddik', N'Director - Mall Operations & Leasing', N'silvi@propertiesinvestment.com', N'Properties Investment'),
(N'Maria Infante', N'Admin. Executive', N'maria.infante@mirdifhills.ae', N'Mirdif Hills'),
(N'Liezyl Magtoto', N'Sr. Administrator', N'liezyl@pidoam.com', N'PID Owners Association Management'),
(N'Sanjeewa Amarasooriya', N'Accountant', N'accounts1@almujama.com', N'Al Mujama Real Estate'),
(N'Ali Abdul Razag', N'Property Executive', N'ali@dirc.ae', N'Dubai Investment Realestate'),
(N'Sabir A', N'Dispatch Coordinator', N'sabir.ahmed@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Ruth Gonzales', N'Administrator', N'ruth.gonzales@altaifinvestment.com', N'Al Taif Investment'),
(N'Sally Moustafa', N'HR and Admin Manager', N'sally.moustafa@ebsl.com', N'Emirates Building System'),
(N'Lawrence Orquillas Villamater', N'Procurement Officer', N'lawrence@ebsl.com', N'Emirates Building System'),
(N'Unnikrishnan Mullacheri', N'Accountant', N'unnikrishnan@pidoam.com', N'PID Owners Association Management'),
(N'Nizar Mowafak Zedan', N'Designer', N'nizar.mowafak@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Faiz Mahmoud Alhayek', N'Dieshop Supervisor', N'faiz@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Srikanth Thota', N'Sr. Design & Estimation Engineer', N'srikanth@ebsl.com', N'Emirates Building System'),
(N'Mohamed Khaled', N'Portfolio Officer', N'm.khaled@almujama.com', N'Al Mujama Real Estate'),
(N'Musaed Al Haj', N'Operation Manager', N'musaed.alhaj@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Limith T.K', N'Accountant', N'limith.tk@ebsl.com', N'Emirates Building System'),
(N'Micah Santiago', N'Executive Secretary', N'micahs@glassllc.co', N'Glass LLC'),
(N'Christian San Jose', N'Warehouse Assistant', N'christian@emiratesglass.com', N'Emirates Glass'),
(N'Saad Iqbal Abdulla', N'Store Keeper', N'sad@ebsl.com', N'Emirates Building System'),
(N'Abedah Ajaj', N'HR & Admin Manager', N'abedah@emiratesglass.com', N'Emirates Glass'),
(N'Vijayan Sethuraman', N'Sr. Checker', N's.vijayan@ebsl.com', N'Emirates Building System'),
(N'Hesham Alghaith', N'General Manager', N'Hesham@pidoam.com', N'PID Owners Association Management'),
(N'Ashly Thomas', N'Project Manager', N'ashly@propertiesinvestment.com', N'Properties Investment'),
(N'Mohammad Ayesh', N'Assistant HR Manager', N'ayesh@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mayadah Awad', N'Assistant Manager – Talent Acquisition', N'mayadah@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Devika Karicheri', N'Accountant', N'devika@dirc.ae', N'Dubai Investment Realestate'),
(N'EBS Central Asia', N'Area Sales Manager – Central Asia, Uzbekistan', N'ebscentralasia@ebsl.com', N'Emirates Building System'),
(N'Sally Moustafa', N'HR Manager', N'sally@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Mirna Ibrahim', N'Executive Assistant', N'Mirna@dirc.ae', N'Dubai Investment Realestate'),
(N'Maen Aljamaeen', N'HR & Admin Officer', N'maen@emiratesglass.com', N'Emirates Glass'),
(N'Ahmed Mohamed Fagiri', N'Sr. Property Executive', N'ahmedfagiri@dirc.ae', N'Dubai Investment Realestate'),
(N'Soltan Zehi Doustin', N'Telesales Executive', N'soltan@dirc.ae', N'Dubai Investment Realestate'),
(N'Yogesh Yadav', N'Lead Developer', N'yogesh@techsource.ae', N'TechSource'),
(N'Rami Mustafa', N'Legal Associate', N'rami.abdellatif@propertiesinvestment.com', N'Properties Investment'),
(N'Ahmad Shokair', N'Senior Associate Digital Marketing', N'ahmad.shokair@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Asma El Mouhadi', N'Sales Admin Manager', N'asma.mouhadi@dirc.ae', N'Dubai Investment Realestate'),
(N'Siby Zachariah', N'Accountant', N'siby@altaifinvestment.com', N'Al Taif Investment'),
(N'Ebtisam Ibrahim', N'HR Officer', N'ebtisam@ebsl.com', N'Emirates Building System'),
(N'Lasitha Nuwanjith', N'Finance Manager', N'lasitha@pidoam.com', N'PID Owners Association Management'),
(N'Subi Kumar', N'Production In charge', N'subi@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Suraj Jain', N'General Manager', N'suraj@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Maria Vel', N'Technical Supervisor', N'maria.vel@almujama.com', N'Al Mujama Real Estate'),
(N'Onab Ezeldin', N'HR Administrative Assistant', N'onab@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohamed Abdalla', N'Collection Supervisor', N'm.abdalla@emiratesglass.com', N'Emirates Glass'),
(N'Shouq AlBannai', N'Design Executive', N'shouq@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Rachel Ann Nazrene', N'Sales Coordinator', N'rachel@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Usman Saleem', N'Software Programmer / Oracle Developer', N'u.saleem@emiratesglass.com', N'Emirates Glass'),
(N'Onoud Al-Ali', N'Associate Sales Director', N'Onoud@dirc.ae', N'Dubai Investment Realestate'),
(N'Faazila Fatimah Wahab', N'Assistant Manager - Internal Audit', N'faazila@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Khaled Alyafei', N'Contract Manager', N'khaled.alyafei@almujama.com', N'Al Mujama Real Estate'),
(N'Adil Abideen', N'Accountant', N'adil@domain.local', N'Properties Investment'),
(N'Joydeep Roy', N'Chief Information Officer', N'jroy@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Karim Salib', N'Regional Sales Manager', N'karim.s@ebsl.com', N'Emirates Building System'),
(N'Shashi Kapoor', N'Mech. Draftsman', N'shashi@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Maryam Alabbasi', N'Sr. Accountant', N'maryam.ahmad@dirc.ae', N'Dubai Investment Realestate'),
(N'EBS KSA', N'Sales & Marketing Africa', N'ebsksa@ebsl.com', N'Emirates Building System'),
(N'Khawla Almheiri', N'Senior Administrative Officer', N'khawla@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ahamed Kalathingal', N'IT Associate', N'ahamed.k@techsource.ae', N'TechSource'),
(N'Basem Abdelhaq', N'Collection Officer', N'b.abdelhaq@emiratesglass.com', N'Emirates Glass'),
(N'Krunal Sorathiya', N'Finance Manager', N'krunal@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Poornima Sankar', N'Secretary', N'poornima.sankar@di-industries.com', N'Dubai Investments Industries'),
(N'Rajul Joshi', N'Oracle Fusion -Technical Consultant', N'rajul@techsource.ae', N'TechSource'),
(N'Muhammad Saleem Awan', N'Sales  Coordinator', N'muhammad.awan@domain.local', N'Emirates Extrusion Factory'),
(N'Gopi Krishna', N'QC engineer', N'gopi@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Mani Bharathi Murugesan', N'Designer', N'mani.b@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Vilma Ronio', N'Document Controller', N'vilma@danahbay.ae', N'Danah Bay'),
(N'Asma Zaid', N'Community Associate', N'asma.zaid@almujama.com', N'Al Mujama Real Estate'),
(N'Tahira Tanveer', N'Accountant', N'tahira@almujama.com', N'Al Mujama Real Estate'),
(N'Emmanuel S Cahilig', N'Store Keeper', N'emmanuel@ebsl.com', N'Emirates Building System'),
(N'Shubham Saraswal', N'Sr. Internal Auditor', N'shubham@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Jobin Chacko', N'Business Development Manager', N'jchacko@litetechind.com', N'Lite-Tech Industries'),
(N'Manal Al Zaabi', N'Business Center Executive', N'manal.alzaabi@dipark.com', N'Dubai Investments Park'),
(N'Ahmed Kalban', N'Façade Architecture Advisor', N'a.kalban@emiratesglass.com', N'Emirates Glass'),
(N'Mohammed Al Shamsi', N'Manager – Investor Relations', N'mohammed.alshamsi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Alya Al Maazmi', N'Sr. Tenant Relation Executive', N'alya@dipark.com', N'Dubai Investments Park'),
(N'Dania Al Mousa', N'Sr. Legal Associate', N'dania@masharie.com', N'Masharie'),
(N'Mohammed Ziyadh', N'Procurement', N'mohammed.ziyadh@dirc.ae', N'Dubai Investment Realestate'),
(N'Fahad Iqbal', N'Purchase Officer', N'', N'White Aluminium Extrusion'),
(N'Joju Francis', N'Mechanical Draftsman', N'joju@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Ameer Basha Kajamoideen', N'Chemist', N'ameer@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Midhun Madhusoodhanan Nair', N'Facility Supervisor MEP', N'midhun@pidoam.com', N'PID Owners Association Management'),
(N'Hawra Sajwani', N'Project Engineer', N'hawra@ebsl.com', N'Emirates Building System'),
(N'Kamil Shamoun', N'Head of Projects – Real Estate Platform', N'kamil.s@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Marwa Al Fayed', N'Administrative Officer', N'marwa@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'eglsecurity', N'Security', N'', N'Emirates Glass'),
(N'Wissam Torbay', N'Sr. Construction Manager', N'wissam.torbay@dirc.ae', N'Dubai Investment Realestate'),
(N'Amos Rajan', N'Sr. Detailer', N'amos.r@ebsl.com', N'Emirates Building System'),
(N'Nica Erika', N'Draftsman', N'n.erika@emiratesglass.com', N'Emirates Glass'),
(N'Lata Jagwani', N'Lead Developer (.NET)', N'lata@techsource.ae', N'TechSource'),
(N'Rohan Pradhan', N'Head of Finance', N'rohan@dipark.com', N'Dubai Investments Park'),
(N'Cindy Marquez', N'Document Controller', N'cindy@domain.local', N'Danah Bay'),
(N'MHD Ghaith Al Sasa', N'Collection In Charge', N'mhd.ghaith@dirc.ae', N'Dubai Investment Realestate'),
(N'Khaled Ali Syed', N'Sr. Accountant', N'khaled.syed@domain.local', N'Properties Investment'),
(N'Gilbert Ward', N'Sr. Commercial Manager', N'gilbert.ward@danahbay.ae', N'Danah Bay'),
(N'Reem Ahmed', N'Sales Admin', N'reem.ahmed@dirc.ae', N'Danah Bay'),
(N'Aamna Alrefai', N'Office Administrator', N'aamna@litetechind.com', N'Lite-Tech Industries'),
(N'Harsh Doshi', N'Senior Tax Manager', N'harsh@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Genevave Bello Gerali', N'FM- Admin', N'genevave@dirc.ae', N'Dubai Investment Realestate'),
(N'Ricodel Borromeo Doringo', N'Procurement Executive', N'rico@ebsl.com', N'Emirates Building System'),
(N'Eldred Madulid Dela Cruz', N'Sales Support Engineer', N'eldred@ebsl.com', N'Emirates Building System'),
(N'Karthikeyan Sampath Kumar', N'Oracle Fusion-CX Consultant', N'karthikeyan@techsource.ae', N'TechSource'),
(N'Gaezelle Tampos', N'Sr. Administrative Officer - Projects', N'gaezelle.t@dipark.com', N'Dubai Investments Park'),
(N'Joseph Chidiac', N'General Manager', N'j.chidiac@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Pranoy John Baby', N'Facility Manager', N'pranoy@pidoam.com', N'PID Owners Association Management'),
(N'Georges Katrib', N'Superintendent Villas', N'georges.katrib@danahbay.ae', N'Danah Bay'),
(N'Masarra Khalifa', N'Marketing Executive', N'masarra@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Muhamed Adeeb Ali', N'Cost Accountant', N'm.adeeb@emiratesglass.com', N'Emirates Glass'),
(N'Adil Mehmood', N'Planner', N'adil.m@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Muhammad Hasnat Ali', N'Sales Coordinator', N'sales@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Mhac Geron', N'Data Entry Personnel', N'mhac@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Eltayeb Osman Ibrahim Younis', N'Project Manager', N'eltayeb@dirc.ae', N'Dubai Investment Realestate'),
(N'Ryan Ledesma', N'Sales Executive', N'ryan.l@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Info EEP', N'Sales Executive', N'', N'Emirates Extruded Polystyrene'),
(N'Jiten Poddar', N'HSE Officer', N'jiten@ebsl.com', N'Emirates Building System'),
(N'Khaled Yousef', N'Projects / Site Engineer', N'khaled@ebsl.com', N'Emirates Building System'),
(N'Akhunzada Muhammed Irfan', N'Data Entry Personel', N'irfan@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Jacob Joseph', N'IT Assistant', N'jacob@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Mohammed Inshaf', N'Graphic Designer', N'm.inshaf@emiratesglass.com', N'Emirates Glass'),
(N'Abdul Rafi', N'Sales Support Engineer', N'abdul.r@ebsl.com', N'Emirates Building System'),
(N'Harshid Sathar', N'Sales Manager', N'harshid@eepdubai.com', N'Emirates Extruded Polystyrene'),
(N'Alamdar Shah', N'Data Entry Operator', N'alamdar@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Sara Al Hashmi', N'Emiratization Specialist', N'sara.alhashmi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Sara Abdulla Ahmed', N'Front Office Coordinator', N'sara.ahmed@ebsl.com', N'Emirates Building System'),
(N'Iuliia Nemi', N'Assistant Manager- Marketing and Specification', N'iuliia@emiratesglass.com', N'Emirates Glass'),
(N'Jeny Thomas', N'Accountant', N'jeny@ebsl.com', N'Emirates Building System'),
(N'Ramesh Kumar', N'Computer Operator', N'ramesh@ebsl.com', N'Emirates Building System'),
(N'Renjith Sundaran', N'Computer Operator', N'', N'Emirates Building System'),
(N'Gouri Nandan', N'Senior Accountant', N'gouri@dipark.com', N'Dubai Investments Park'),
(N'Dinto David', N'Design Engineer', N'dinto@ebsl.com', N'Emirates Building System'),
(N'Sanchita Vazerkar', N'Assistant Manager - Risk', N'sanchita@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ali Hussain', N'Head of Risk', N'ali.hussain@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Irfan Ali', N'Store Keeper', N'irfan.ali@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Muhammad Zain', N'Data Entry Operator', N'zain@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Sanjay Sanghavi', N'Head Of Finance', N'sanjay@dirc.ae', N'Dubai Investment Realestate'),
(N'Sathish Kumar Srinivasan', N'Sr. Detailer', N'sathish.k@ebsl.com', N'Emirates Building System'),
(N'Ahmad Dibajeh', N'Assistant Manager – QA/QC', N'a.dibajeh@emiratesglass.com', N'Emirates Glass'),
(N'Amer Ahli', N'PRO', N'amer.ahli@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Philomina Leo Miranda', N'Finance Executive', N'philomina@pidoam.com', N'PID Owners Association Management'),
(N'Rashed Al Jarwan', N'Senior Operations Manager', N'rashed.aljarwan@glassllc.co', N'Glass LLC'),
(N'Nadeem Usama', N'Financial Analyst', N'n.usama@glassllc.co', N'Glass LLC'),
(N'Larson Dheesmas', N'Sales  Coordinator', N'salesmarketing2@whiteextrusion.com', N'Emirates Extrusion Factory'),
(N'Ashik Najeem', N'Data Entry Personnel', N'ashik@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Nazera Shabnam', N'Oracle Fusion – HCM Consultant', N'nazera@techsource.ae', N'TechSource'),
(N'Cesar Figueroa', N'Dispatcher Forman', N'cesar@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Osama Hallak', N'Sales Manager', N'o.hallak@emiratesglass.com', N'Emirates Glass'),
(N'Arshad Ali', N'Warehouse Executive', N'arshad.ali@emiratesglass.com', N'Emirates Glass'),
(N'Abouelkheir Negm', N'Portfolio Officer', N'abouelkheir@almujama.com', N'Al Mujama Real Estate'),
(N'Shilpa Sukumar', N'Assistant Manager-Finance', N'shilpa.s@di-industries.com', N'Dubai Investments Industries'),
(N'Ali Sheikh', N'Administrative Assistant', N'ali.sheikh@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Nour Al Koudat Succari', N'Leasing Director', N'nour@dirc.ae', N'Dubai Investment Realestate'),
(N'Danish Dabir', N'Accountant', N'danish.dabir@dirc.ae', N'Dubai Investment Realestate'),
(N'Imrose Ahmed', N'General Manager Sales & Marketing', N'imrose@litetechind.com', N'Lite-Tech Industries'),
(N'Mojahid Sorkatti', N'Portfolio Officer', N'mojahid@almujama.com', N'Al Mujama Real Estate'),
(N'Udhay Bhavimani', N'Sr. Design & Estimation Engineer', N'udhay.b@ebsl.com', N'Emirates Building System'),
(N'Jayaprasanth Thirumurthy', N'Design Engineer', N'j.prasanth@ebsl.com', N'Emirates Building System'),
(N'Marwan Isber', N'Superintendent', N'marwan@dipangola.com', N'DIP Angola'),
(N'Wini Miala', N'Public Relation Officer', N'wini@dipangola.com', N'DIP Angola'),
(N'Ivaldiria Mendes', N'Business Development Manager', N'ivamendes@dipangola.com', N'DIP Angola'),
(N'Shaik Muzamil', N'Sr. Accountant', N'muzamil@dipangola.com', N'DIP Angola'),
(N'Gopinath Selvaraj', N'Sr.Detailer', N'gopi.s@ebsl.com', N'Emirates Building System'),
(N'Ashwaq Ahmed', N'Admin. Assitant', N'ashwaq@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Jawahair Obaid', N'Receptionist', N'', N'White Aluminium Extrusion'),
(N'Fady Kayyal', N'Chief Corporate Affairs Officer', N'fady@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohammad Akmal', N'Accountant', N'mohammad.akmal@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ayesha AlHammadi', N'Accountant', N'ayesha@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Raghul Sasidharan', N'Assistant Manager- Production', N'raghul@emiratesglass.com', N'Emirates Glass'),
(N'Ahmed Samy Fattoh', N'Store Keeper', N'ahmed.s@ebsl.com', N'Emirates Building System'),
(N'Vijaya Anand Uttarkar', N'Sr. Projects Manager', N'vijay.anand@ebsl.com', N'Emirates Building System'),
(N'Hamda Alderei', N'Document Controller', N'hamda@danahbay.ae', N'Danah Bay'),
(N'Mohammad Basheer', N'Sales Executive', N'm.basheer@domain.local', N'Emirates Glass'),
(N'Philip Andria Dela Cruz Geronimo', N'Document Controller', N'philip@ebsl.com', N'Emirates Building System'),
(N'John Kevin Manibo Tabios', N'Project Coordinator', N'john.kevin@ebsl.com', N'Emirates Building System'),
(N'Amer Mohammed', N'Collection', N'amer.mohammed@dirc.ae', N'Dubai Investment Realestate'),
(N'Angela Catherine', N'Receptionist', N'angela@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Suresh Rajendran', N'Sr. Detailer', N'suresh.r@ebsl.com', N'Emirates Building System'),
(N'Fatma Al Ali', N'Production Administrative Coordinator (Plant)', N'fatma.ali@ebsl.com', N'Emirates Building System'),
(N'Heba Aziz', N'Design Engineer', N'heba@ebsl.com', N'Emirates Building System'),
(N'Ameer Sohail', N'Sales Assistant', N'ameer.sohail@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Rey Anthony Ruel Sumiller', N'HSE Officer', N'r.antony@ebsl.com', N'Emirates Building System'),
(N'Muneer Badharul', N'Senior HAVAC Technician', N'muneer@altaifinvestment.com', N'Al Taif Investment'),
(N'Mohammed Aadhil', N'Tax Analyst', N'm.aadhil@emiratesglass.com', N'Emirates Glass'),
(N'Satya Viswanadh Pidaparty', N'Engineering Supervisor', N'satya.v@ebsl.com', N'Emirates Building System'),
(N'Aslam Rasak', N'Senior HAVAC Technician', N'aslam.rasak@altaifinvestment.com', N'Al Taif Investment'),
(N'Alaa Mansoor', N'Head of Compliance', N'alaa.mansoor@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Wasim Shaikhs', N'Civil Technician', N'wasims@altaifinvestment.com', N'Al Taif Investment'),
(N'Anand Durai', N'Senior Checker', N'anand.d@ebsl.com', N'Emirates Building System'),
(N'Bikram Ghimire', N'Plumber', N'bikram@altaifinvestment.com', N'Al Taif Investment'),
(N'Fatima Badr', N'Brand Marketing Executive', N'fatimabadr@emiratesglass.com', N'Emirates Glass'),
(N'Ravindran Venkadasamy', N'Buyer', N'ravindran@litetechind.com', N'Lite-Tech Industries'),
(N'Vijayakumar Devaraj', N'Warehouse Supervisor', N'vijayakumar@emiratesglass.com', N'Emirates Glass'),
(N'Geoffery Jerald', N'Accountant', N'j.geoffery@ebsl.com', N'Emirates Building System'),
(N'Ramaswamy Athmanathan', N'Detailer', N'r.swamy@ebsl.com', N'Emirates Building System'),
(N'Alan Babu', N'Computer Operator', N'', N'Emirates Building System'),
(N'Jose Van Alipao Dela Cruz', N'Detailer', N'v.jose@ebsl.com', N'Emirates Building System'),
(N'Anish Bhasurangan', N'Project Manager', N'b.anish@ebsl.com', N'Emirates Building System'),
(N'Javed Mumtaz Khan', N'Warehouse Assistant', N'j.mumtaz@emiratesglass.com', N'Emirates Glass'),
(N'Parwez Alam Khan', N'Warehouse Assistant', N'p.alam@emiratesglass.com', N'Emirates Glass'),
(N'Rathul Pookkottil', N'Asst. Designer', N'rathul@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Syed Salauddin', N'Production Manager', N'syed.salauddin@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Jaydeep Chhabhaya', N'Assistant Finance Manager', N'jaydeep@dirc.ae', N'Dubai Investment Realestate'),
(N'Amala Rathees', N'Data Entry Personnel', N'amala@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Prasanth Cyriac', N'Dieshop supervisor', N'prasanth.c@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Ritesh Kumar Agarwal', N'Sr.Finance Manager', N'ritesh@altaifinvestment.com', N'Al Taif Investment'),
(N'Est Coordinator', N'Estimation Coordinator', N'est.coordinator@ebsl.com', N'Emirates Building System'),
(N'Ana Julia Pinho', N'Admin. Officer', N'ana@domain.local', N'DIP Angola'),
(N'Aravind Jayan bindu', N'Sales Coordinator', N'aravind@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Rohit Pagarani', N'Investment Manager', N'rohit@diinvestmentholding.com', N'DI Investment Holding Limited'),
(N'Noor Al Marzooqi', N'Legal Trainee', N'noor.almarzooqi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohammad Shahnawazul', N'Logistics Supervisor', N'mohammad.s@ebsl.com', N'Emirates Building System'),
(N'Rajkumar Ganesan', N'Document Controller', N'raj.g@ebsl.com', N'Emirates Building System'),
(N'Lojayne Bakr', N'Document Controller', N'lojayne@almujama.com', N'Al Mujama Real Estate'),
(N'Tharish Kareem', N'Accountant', N'tharish@almujama.com', N'Al Mujama Real Estate'),
(N'Donnel Apao Saldia', N'Planning Officer', N'donnel@ebsl.com', N'Emirates Building System'),
(N'Michael Bughao Tingson', N'HSE Officer', N'michael.b@ebsl.com', N'Emirates Building System'),
(N'Dixon Tapilot Olan Olan', N'HSE Officer', N'dixon.t@ebsl.com', N'Emirates Building System'),
(N'Dick Johns', N'Technical Engineer', N'dick.johns@litetechind.com', N'Lite-Tech Industries'),
(N'Priyanka Saha', N'Accountant', N's.priyanka@ebsl.com', N'Emirates Building System'),
(N'Ahmad Alqudah', N'Senior Sales Manager', N'ahmad.alqudah@domain.local', N'Emirates Glass'),
(N'Raymond Manuyag', N'Supervisor', N'r.manuyag@ebsl.com', N'Emirates Building System'),
(N'Roman Mendoza', N'Supervisor', N'r.mendoza@ebsl.com', N'Emirates Building System'),
(N'Turky Yousef Aokan', N'Supervisor', N't.yousef@ebsl.com', N'Emirates Building System'),
(N'Dilip Poojari', N'Document Controller', N'dilip.p@ebsl.com', N'Emirates Building System'),
(N'Nidhi Singhvi', N'Financial Controller', N'nidhi@dipark.com', N'Dubai Investments Park'),
(N'Amna Fahad Ibrahim', N'Cashier', N'amna.lootah@dipark.com', N'Dubai Investments Park'),
(N'Arvie Padilla', N'Expeditor', N'arvie@ebsl.com', N'Emirates Building System'),
(N'Imrul Khys', N'MEP Supervisor', N'imrul@pidoam.com', N'PID Owners Association Management'),
(N'Mohammed Salim', N'Operator', N'm.salim@emiratesglass.com', N'Emirates Glass'),
(N'John Robert', N'Project Engineer', N'john.r@ebsl.com', N'Emirates Building System'),
(N'Ismail Kappil', N'Storekeeper', N'ismail.k@ebsl.com', N'Emirates Building System'),
(N'Mohd Saleem', N'QA & QC Inspector', N'mohd.s@ebsl.com', N'Emirates Building System'),
(N'Hamda Ahmad', N'Front Office Cooedinator', N'hamda.ahmad@ebsl.com', N'Emirates Building System'),
(N'Roshan Kumar Pandey', N'Security Guard', N'roshan.pandey@dirc.ae', N'Dubai Investment Realestate'),
(N'Hermie Salvador Jandusay', N'Expidator', N'hermie@ebsl.com', N'Emirates Building System'),
(N'Mohammed Yousef', N'Projects Engineer', N'm.yousef@ebsl.com', N'Emirates Building System'),
(N'Syed Anas Shabbir', N'Junior Accountant', N'syed.anas@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Shafeer Parakkat Sidhick', N'Procurement Executive', N'shafeer@emiratesglass.com', N'Emirates Glass'),
(N'Jake Robert Musa Salazar', N'Machine Operator', N'', N'Emirates Building System'),
(N'Abedalaziz Dalky', N'Assistant Manager - Production', N'a.dalky@emiratesglass.com', N'Emirates Glass'),
(N'Antoine Abi Rached', N'Group General Counsel', N'antoine@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Khalifa Bin Hashim', N'Sr. Development Manager', N'khalifa.binhashim@dirc.ae', N'Dubai Investment Realestate'),
(N'Nishmita Poojary', N'Finance Executive', N'nishmita@pidoam.com', N'PID Owners Association Management'),
(N'Tamer Younis', N'Senior Project Engineer', N'tamer@ebsl.com', N'Emirates Building System'),
(N'Prinu Sankar', N'Accountant', N'prinu@almujama.com', N'Al Mujama Real Estate'),
(N'Aayushi Gujral', N'Accountant', N'aayushi@almujama.com', N'Al Mujama Real Estate'),
(N'Mutharasan Govindaraj', N'Detailer', N'm.raj@ebsl.com', N'Emirates Building System'),
(N'Noorudheen Aboobacker', N'Electrician', N'noorudheen@altaifinvestment.com', N'Al Taif Investment'),
(N'Maleeha Mohammad', N'Customer Service Executive', N'maleeha@emiratesglass.com', N'Emirates Glass'),
(N'Julius Dexter Rosito', N'Community Admin', N'julius@pidoam.com', N'PID Owners Association Management'),
(N'Akshai', N'Assistant Manager ERP', N'akshai@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Abbas Ali', N'Supply Chain Manager', N'abbas.ali@emiratesglass.com', N'Emirates Glass'),
(N'Maneesh Mani M', N'IT Support Administrator', N'maneesh@ebsl.com', N'Emirates Building System'),
(N'Khalid Al Daboos', N'Senior Operation Manager', N'k.aldaboos@glassllc.co', N'Glass LLC'),
(N'Genalyn Cagatin', N'Community Service Executive', N'genalyn.cagatin@pidoam.com', N'PID Owners Association Management'),
(N'Alia Al Hashmi', N'IT Coordinator', N'alia.alhashmi@techsource.ae', N'TechSource'),
(N'Saeed Ahmed Saeed Abdelraouf', N'Sr. Project Engineer', N'saeed.ahmed@ebsl.com', N'Emirates Building System'),
(N'Sooraj Ramakrishna Pillai', N'Technical Executive', N'sooraj@emiratesglass.com', N'Emirates Glass'),
(N'Hala Mohammad', N'Customer Service Executive', N'hala@emiratesglass.com', N'Emirates Glass'),
(N'Kaladhar Das', N'Plant Manager', N'kdas@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Naveen Kumar Gummadi', N'Safety Officer', N'naveen@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Nibin Tholath', N'Assistant Storekeeper', N'nibin.t@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Mazhood', N'HSE Officer', N'mazhood@ebsl.com', N'Emirates Building System'),
(N'Azad Sirajudin', N'HSE Officer', N'azad.s@ebsl.com', N'Emirates Building System'),
(N'Sanad', N'HSE Officer', N'sanad@ebsl.com', N'Emirates Building System'),
(N'Amir Abdullhaq Adhikari', N'Lab. Chemist', N'amir@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'EBS Production', N'Generic Email (Production)', N'ebsprd@ebsl.com', N'Emirates Building System'),
(N'Hilal Mahdi', N'Marketing & Specification Manager', N'hilal@emiratesglass.com', N'Emirates Glass'),
(N'Mohammad Sajjad Tameez', N'Accountant', N'sajjad@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Tiago Carneiro - DIP Angola', N'General Manager', N'tiago@dipangola.com', N'DIP Angola'),
(N'Mehdi Benmoussa', N'Sales Manager', N'mehdi@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Fouad Kassabaki', N'Business Development Executive', N'ebsbd@ebsl.com', N'Emirates Building System'),
(N'Asem Majed Numan Alkhudari', N'Sales Engineer', N'asem@litetechind.com', N'Lite-Tech Industries'),
(N'Charissa Nicolas Morante', N'Sales Coordinator', N'charissa@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Vinod Raveendran', N'Accountant', N'vinod.r@di-industries.com', N'Dubai Investments Industries'),
(N'Mohamed Khan', N'Accountant', N'm.khan@dipark.com', N'Dubai Investments Park'),
(N'Ayesha Albalooshi', N'Receptionist', N'ayesha.albalooshi@dirc.ae', N'Dubai Investment Realestate'),
(N'Sowmiya Ilangovan', N'Purchase Manager', N'sowmiya@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Khadka Bahadur', N'Storekeeper Assistant', N'', N'Gulf Metal Craft'),
(N'Juan Marziotte', N'Head of Finance', N'juan@di-industries.com', N'Dubai Investments Industries'),
(N'Fajer Albooshi', N'Front Office Coordinator', N'a.fajer@ebsl.com', N'Emirates Building System'),
(N'Haneen Alblooshi', N'Document Controller', N'haneen@ebsl.com', N'Emirates Building System'),
(N'Armaan Mody', N'Executive Assistant & Financial Coordinator', N'armaan@dirc.ae', N'Dubai Investment Realestate'),
(N'Shahmir Hussain', N'Head of Finance', N'shahmir@glassllc.co', N'Glass LLC'),
(N'Pragati Rijal', N'Accountant', N'pragati@di-industries.com', N'Dubai Investments Industries'),
(N'Ahmed Samara', N'Project Manager', N'ahmed.samara@ebsl.com', N'Emirates Building System'),
(N'Thani Almheiri', N'Assistant Accountant', N'thani.almheiri@emiratesglass.com', N'Emirates Glass'),
(N'Alawia Farah', N'Business Center Executive', N'alawia@dipark.com', N'Dubai Investments Park'),
(N'Hanan Abdulla Alblooshi', N'Front Office Coordinator', N'a.hanan@ebsl.com', N'Emirates Building System'),
(N'Ram Dhivakar Krishnamoorthy', N'Painting Inspector', N'ram.d@ebsl.com', N'Emirates Building System'),
(N'Afra Almutawa', N'Sales Support', N'afra.m@litetechind.com', N'Lite-Tech Industries'),
(N'Arjun Sreenivas', N'Technical Support Manager', N'arjun.s@litetechind.com', N'Lite-Tech Industries'),
(N'Fatma Alkhajeh', N'Sales Support', N'fatma.n@litetechind.com', N'Lite-Tech Industries'),
(N'Elyazya Almarzooqi', N'Senior HR & Admin Executive', N'elyazya@emiratesglass.com', N'Emirates Glass'),
(N'EBS Intern', N'Intern', N'ebsintern@ebsl.com', N'Emirates Building System'),
(N'Bilal Sheikh', N'Sales Representative', N'salespk@ebsl.com', N'Emirates Building System'),
(N'Rohit Varshney', N'Finance Manager', N'rohit.varshney@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Aditya Kumar', N'Assistant Supervisor - Production', N'aditya@emiratesglass.com', N'Emirates Glass'),
(N'Amit Kumar', N'Assistant Supervisor - Production', N'amit.kumar@emiratesglass.com', N'Emirates Glass'),
(N'Akshay Shaju', N'Assistant Supervisor - Production', N'akshay@emiratesglass.com', N'Emirates Glass'),
(N'Vipinkumar Vishwanathan Nair', N'Supervisor - Production', N'vipinkumar@emiratesglass.com', N'Emirates Glass'),
(N'Vyshnavdas Manaparambil Devadas', N'Material Movement Operator', N'vyshnavdas@emiratesglass.com', N'Emirates Glass'),
(N'Manesh Kolangatt', N'Die Shop Supervisor', N'dieshop@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Matee Ur Rehman', N'Sales  Coordinator', N'matee.rehman@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Manoj Kumar Kammili', N'Sr.Detailer', N'k.manoj@ebsl.com', N'Emirates Building System'),
(N'Maryam Alrashidi', N'Receptionist', N'maryam.alrashidi@dipark.com', N'Dubai Investments Park'),
(N'Nishad Abdulla', N'Purchase Officer', N'nishadabdulla@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Gerir Mohamed', N'Sales Representative', N'gerirmohamed@whiteextrusion.com.', N'White Aluminium Extrusion'),
(N'Mark Jayson', N'Computer Operator', N'mark.j@ebsl.com', N'Emirates Building System'),
(N'Dona Chacko', N'Community Service Executive', N'dona.chacko@pidoam.com', N'PID Owners Association Management'),
(N'Mahra Al Mutawei', N'Data Entry Officer', N'mahra@dipark.com', N'Dubai Investments Park'),
(N'Shaikha Alfarsi', N'Revenue Executive', N'shaikha@dipark.com', N'Dubai Investments Park'),
(N'Guia Kaye Sardido', N'Community Service Executive', N'guia@pidoam.com', N'PID Owners Association Management'),
(N'Sudhir Maindan', N'ERP Project Manager', N'sudhir.r@ebsl.com', N'Emirates Building System'),
(N'Mohamed Adil', N'Portfolio Manager', N'm.adil@pidoam.com', N'PID Owners Association Management'),
(N'Rasel Mazumder', N'Security & Facility Supervisor', N'rasel.m@ebsl.com', N'Emirates Building System'),
(N'Rajesh Kumar', N'Senior Design Engineer', N'rajesh.k@ebsl.com', N'Emirates Building System'),
(N'Nivin Sundara', N'Senior Detailer', N'nivin@ebsl.com', N'Emirates Building System'),
(N'HSE Emirates Glass', N'HSE', N'hse@emiratesglass.com', N'Emirates Glass'),
(N'Ramkrishna Subhash Patil', N'Maintenance Manager', N'ramkrishna@emiratesglass.com', N'Emirates Glass'),
(N'Mais Sowidan', N'Estimator', N'mais.sowidan@emiratesglass.com', N'Emirates Glass'),
(N'Sherin Sunil Mathew', N'Warehouse Executive', N'sherin.mathew@emiratesglass.com', N'Emirates Glass'),
(N'Rajasekaran Periyasamy', N'Sr. Checker', N'r.sekaran@ebsl.com', N'Emirates Building System'),
(N'Chandana Chandran', N'HSE Officer', N'chandan@ebsl.com', N'Emirates Building System'),
(N'Rajeswararao Busa', N'Sr. Detailer', N'r.rao@ebsl.com', N'Emirates Building System'),
(N'Sara Al Mustafa', N'Legal Assistant', N'sara.a@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohammad Anowar', N'Packing Forman', N'packing@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Muhammad Amjad', N'Anodizing Forman', N'anod@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Muhammad Yousaf', N'Powder Coating Forman', N'pcoating@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Kamal Abdul Karim', N'Press Operator', N'pressprod@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Victor Landong', N'Computer Operator', N'victor@ebsl.com', N'Emirates Building System'),
(N'Greeshma Parapurath Sarasan', N'Accountant', N'greeshma@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Syed Sharjeel Hashmi', N'Sales Engineer', N'sharjeel@litetechind.com', N'Lite-Tech Industries'),
(N'Mohamed Khalifa', N'Senior Sales Executive', N'mohamed.khalifa@ebsl.com', N'Emirates Building System'),
(N'Subash Karki', N'Procurement Assistant', N'subash@ebsl.com', N'Emirates Building System'),
(N'Muhammed Safeek', N'Manager Internal Audit', N'm.safeek@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Qasim Alrijjal', N'Sr. Marketing Manager', N'qasim@dirc.ae', N'Dubai Investment Realestate'),
(N'Anith Zacharia', N'HR & Payroll Officer', N'anith.j@ebsl.com', N'Emirates Building System'),
(N'Amajala Sateesh', N'Sr. Detailer', N'a.sateesh@ebsl.com', N'Emirates Building System'),
(N'Rajasekar Reddy Peddinti', N'Sr. Design Engineer', N'r.reddy@ebsl.com', N'Emirates Building System'),
(N'Ritesh Kumar', N'Finance Manager', N'ritesh@propertiesinvestment.com', N'Properties Investment'),
(N'Farah Eissa', N'Receptionist cum Admin', N'farah.eissa@propertiesinvestment.com', N'Properties Investment'),
(N'Amal Satheesan', N'Planning Engineer', N'amal@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Neha Prasad', N'MCA Consultant', N'neha.p@propertiesinvestment.com', N'Properties Investment'),
(N'Mohamed Alali', N'Sales Executive', N'mohamed.alali@emiratesglass.com', N'Emirates Glass'),
(N'Dina Abdul Malak', N'Sales Executive', N'', N'Emirates Glass'),
(N'Vishal Katyare', N'Project Manager', N'vishal.k@techsource.ae', N'TechSource'),
(N'Maha Aldhaheri', N'HR/Marketing cum Administration Manager', N'maha@altaifinvestment.com', N'Al Taif Investment'),
(N'Herin John', N'HSE Officer', N'herin@ebsl.com', N'Emirates Building System'),
(N'Arun Kumar', N'HSE Officer', N'a.kumar@ebsl.com', N'Emirates Building System'),
(N'Ajay Dev', N'HSE Officer', N'd.ajay@ebsl.com', N'Emirates Building System'),
(N'Yousuf Taher', N'Internal Auditor', N'yousuf.taher@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Maha Faisal', N'HR Administrator', N'maha.faisal@ebsl.com', N'Emirates Building System'),
(N'Genie Manzano', N'HR Assistant', N'genie.manzano@emiratesglass.com', N'Emirates Glass'),
(N'Abdul Azzez Chelakkodan', N'Cost Accountant', N'a.chelakkodan@emiratesglass.com', N'Emirates Glass'),
(N'Nidhin Babu', N'Production Planning Officer', N'nidhin.b@ebsl.com', N'Emirates Building System'),
(N'Raj Kumar', N'Hand-Over Officer', N'raj.kumar@dirc.ae', N'Dubai Investment Realestate'),
(N'Wang Yuzhe', N'Country Manager', N'', N'Lite-Tech Industries'),
(N'Salem Al Suwaidi', N'AML Focal Point', N'salem.a@dipark.com', N'Dubai Investments Park'),
(N'Navaneeth Anandan', N'HOA Manager', N'navaneeth@pidoam.com', N'PID Owners Association Management'),
(N'Hissa AlShehhi', N'Brand marketing executive', N'hissa@emiratesglass.com', N'Emirates Glass'),
(N'Alya Mohamed', N'Front Office Coordinator', N'alya.m@ebsl.com', N'Emirates Building System'),
(N'Anand Krishna', N'HSE Officer', N'anand.krishna@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Venkata Vara Prasad Kolungundla', N'Senior Maintenance Engineer', N'venkata@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Vaneet Kumar', N'Designer', N'vaneet.kumar@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Nidhin Kannan', N'Storekeeper Assit', N'nidhin.kannan@gulfmetalcraft.com', N'Gulf Metal Craft'),
(N'Shrouk Barakat', N'Projects Manager', N'shrouk@ebsl.com', N'Emirates Building System'),
(N'Ashif Aqbal Khan', N'HSE Manager', N'ashif.k@ebsl.com', N'Emirates Building System'),
(N'Jith Babu Sivaprasadpillai', N'Sr. Executive -Warehouse & Inventory', N'j.babu@ebsl.com', N'Emirates Building System'),
(N'Salem Mayed', N'Internal Auditor', N'salem.mayed@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ahmed Mohamed Farag  Abdou', N'Sales Engineer', N'ahmed.mohamed@litetechind.com', N'Lite-Tech Industries'),
(N'Koushal Pralhad Sharma', N'Production Planning Engineer', N'koushal@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Brune Christo Christopher', N'Inventory Controller', N'brune@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Ali Jibril', N'Executive VP Sales and Operation', N'ali.jibril@dirc.ae', N'Dubai Investment Realestate'),
(N'Surya QC', N'Senior QC Engineer', N't.surya@ebsl.com', N'Emirates Building System'),
(N'Anil Kumar Reddy', N'Sr. Detailer', N'r.anil@ebsl.com', N'Emirates Building System'),
(N'Yousuf Akber Ali Karimi', N'CFO', N'yaali@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Harun Arakkal', N'Assistant Manager – Sales - Digital Printing', N'harun@emiratesglass.com', N'Emirates Glass'),
(N'Nikolay Kolomiychenko', N'General Manager', N'nikolay@glassllc.co', N'Glass LLC'),
(N'Mohammed Alteneiji', N'PRO', N'mohammed.alteneiji@dirc.ae', N'Dubai Investment Realestate'),
(N'Saif Bin Masood', N'HR Assistant', N'saif@emiratesglass.com', N'Emirates Glass'),
(N'Deepak Kumar', N'Senior Design & Estimation Engineer', N'deepak@ebsl.com', N'Emirates Building System'),
(N'Barani Baskar', N'Sr. Detailer', N'b.baskar@ebsl.com', N'Emirates Building System'),
(N'Kelington Rasaiah', N'ERP Programmer Analyst', N'kelington@masharie.com', N'Masharie'),
(N'Elias Moufarrej', N'Sales Representative - Africa', N'elias@ebsl.com', N'Emirates Building System'),
(N'Ramya Rajagopalan', N'Business Analyst', N'ramya@dipark.com', N'Dubai Investments Park'),
(N'Sunil Kumar', N'Design Engineer', N'k.sunil@ebsl.com', N'Emirates Building System'),
(N'Abdullah Kanaan', N'Project Manager', N'abdullah.k@dipark.com', N'Dubai Investments Park'),
(N'Conceicao Honjo', N'Sr. Accountant', N'Conceicao@dipangola.com', N'DIP Angola'),
(N'Aswanth Puthiya Veettil', N'Civil Tech', N'aswanth@altaifbc.com', N'Al Taif Investment'),
(N'Michael Jao', N'MDM Officer', N'michael.jao@techsource.ae', N'TechSource'),
(N'Chandra Goud Ediga', N'Quality Officer', N'chandra@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Raghupathy Boopathy', N'Sr. Checker', N'r.boopathy@ebsl.com', N'Emirates Building System'),
(N'Pazhanivel Chandrasekar', N'Sr. Detailer', N'p.shekar@ebsl.com', N'Emirates Building System'),
(N'Govindaraman Ramamurthy', N'Sr. Design & Estimation Engineer', N'r.govind@ebsl.com', N'Emirates Building System'),
(N'Helal Ahmad Khan', N'HSE Officer', N'helal.k@ebsl.com', N'Emirates Building System'),
(N'Rahul Ram Padmanaba Pillai', N'HSE Officer', N'r.rahul@ebsl.com', N'Emirates Building System'),
(N'Ajith K P', N'HSE Officer', N'k.ajith@ebsl.com', N'Emirates Building System'),
(N'Jennifer Gomes', N'HR Manager', N'jennifer@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Anoud Bader Helal Althehli', N'Front Office Coordinator', N'anoud.b@ebsl.com', N'Emirates Building System'),
(N'Maha Essa Ahmed Mibarak', N'Front Office Coordinator', N'maha.essa@ebsl.com', N'Emirates Building System'),
(N'Johnases Navarro Lapitan', N'Computer Operator', N'n.john@ebsl.com', N'Emirates Building System'),
(N'Aishwarya Nanda', N'Investment Analyst', N'aishwarya.n@diinvestmentholding.com', N'DI Investment Holding Limited'),
(N'Akhil Vishnu', N'Purchase officer', N'akhil.v@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Fatmah Mohamed Hassan', N'Marketing and Coordination Executive', N'fatmah@altaifinvestment.com', N'Al Taif Investment'),
(N'Abdullah Al-Rashdi', N'Compliance Officer', N'abdullah.alrashdi@pidoam.com', N'PID Owners Association Management'),
(N'Nazia Hussain', N'Executive Assistant - COO', N'nazia@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Ahmed Woldghamail', N'Head of Security', N'ahmed.w@dipark.com', N'Dubai Investments Park'),
(N'Ramesh Reddy', N'Consultant', N'ramesh.reddy@dirc.ae', N'Dubai Investment Realestate'),
(N'Mazen Sayed', N'Site Security', N'mazen@dipark.com', N'Dubai Investments Park'),
(N'Neeraj Singh', N'Accountant', N'neeraj.singh@propertiesinvestment.com', N'Properties Investment'),
(N'Adru Ravi', N'Sr. Checker', N'a.ravi@ebsl.com', N'Emirates Building System'),
(N'Malaiyarasan Masanam', N'Sr. Checker', N'm.arasan@ebsl.com', N'Emirates Building System'),
(N'Prakash Ganeshan', N'Sr. Detailer', N'p.ganesh@ebsl.com', N'Emirates Building System'),
(N'MD Mojahid', N'Sr Production Supervisor', N'm.mojahid@ebsl.com', N'Emirates Building System'),
(N'Nada Shahab Ahmad', N'Receptionist', N'nada.shahab@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Maitha Alblooshi', N'Sales Coordinator', N'maitha.a@ebsl.com', N'Emirates Building System'),
(N'Hind Alhashmi', N'IT Project Coordinator', N'hind.alhashmi@techsource.ae', N'TechSource'),
(N'Iman Jasim', N'Receptionist', N'iman.jasim@dipark.com', N'Dubai Investments Park'),
(N'Salim Hussanar', N'Facility Engineer', N'salim.h@altaifinvestment.com', N'Al Taif Investment'),
(N'Mannan Shafiq', N'Chief Accountant', N'mannan@emiratesglass.com', N'Emirates Glass'),
(N'Ayah Shakir Alblooshi', N'Sales Coordinator', N'ayah.s@ebsl.com', N'Emirates Building System'),
(N'Amit K. Rathod', N'Oracle Fusion - Finance Consultant', N'amit.r@techsource.ae', N'TechSource'),
(N'Snehal Dsouza', N'Temporary Business Center Executive', N'snehal@dipark.com', N'Dubai Investments Park'),
(N'Sona Johnson', N'Accountant', N'sona@litetechind.com', N'Lite-Tech Industries'),
(N'Ralf Katrib', N'Internship', N'ralf.katrib@dirc.ae', N'Dubai Investment Realestate'),
(N'Djamila Evaristo', N'HR/Admin Executive', N'djamila@dipangola.com', N'DIP Angola'),
(N'Thanseeh Salam Kuttichadayan', N'Facility Admin', N'thanseeh@pidoam.com', N'PID Owners Association Management'),
(N'Hamad Zahed', N'Receptionist', N'h.zahed@emiratesglass.com', N'Emirates Glass'),
(N'Salha Mohammad', N'Receptionist', N'salha@dipark.com', N'Dubai Investments Park'),
(N'Linsa Sam', N'Estimation Engineer', N'linsa@litetechind.com', N'Lite-Tech Industries'),
(N'Anand Vishnu', N'Safety Officer', N'anand.v@whiteextrusion.com', N'White Aluminium Extrusion'),
(N'Kenneth Ivan', N'IT Assistant', N'kenneth@emiratesglass.com', N'Emirates Glass'),
(N'Khaled Alblooshi', N'HSE Officer', N'a.khaled@ebsl.com', N'Emirates Building System'),
(N'Moadhafar Al Huseini', N'Compliance Supervisor', N'moadhafar@almujama.com', N'Al Mujama Real Estate'),
(N'Afra Alhemeiri', N'Sr. Compliance Officer', N'afra.alhemeiri@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Angela Custodio Sareno', N'Executive Secretary', N'Angela.Custodio@Dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Adnan Shah', N'Chemist', N'adnan.shah@emiratesextrusion.com', N'Emirates Extrusion Factory'),
(N'Ahmad Al Falasi', N'Receptionist Ground Floor', N'a.alfalasi@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Maha Al Ghareeb', N'Risk Administrator', N'maha.a@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Mohammad Ishtiyaq Uddin', N'Sales Manager', N'm.ishtiyaq@ebsl.com', N'Emirates Building System'),
(N'Abdulla Mohammed Alzaabi', N'Project Coordinator', N'a.mohammed@ebsl.com', N'Emirates Building System'),
(N'Mohammed Bin Zubair', N'Accountant', N'', N'Properties Investment'),
(N'Sara Almulla', N'Leasing Officer', N'sara.almulla@dirc.ae', N'Dubai Investment Realestate'),
(N'Mezna Almerwi', N'Receptionist', N'mezna.almerwi@dirc.ae', N'Dubai Investment Realestate'),
(N'Fahad Arif', N'QC Supervisor', N'fahad.arif@emiratesglass.com', N'Emirates Glass'),
(N'Arun Elavarasan', N'Detailer', N'e.arun@ebsl.com', N'Emirates Building System'),
(N'Arunachalam Jothi Ramalingam', N'Detailer', N'', N'Emirates Building System'),
(N'Francisco Ferreira', N'Project Accountant', N'francisco@dipark.com', N'Dubai Investments Park'),
(N'Lokman Amasha', N'Sales Manager', N'lokman@dirc.ae', N'Dubai Investment Realestate'),
(N'Adarsh Mathew Thomas', N'Sr. Tax Analyst', N'adarsh.m@dubaiinvestments.com', N'Dubai Investments PJSC'),
(N'Pooja Jain', N'EPM Consultant', N'pooja@techsource.ae', N'TechSource');

/* The export's company names mapped onto vms.Entity, where the two spell the
   same company differently. Editable: add a row here and re-run.

   A company with no row here still links if an entity of exactly that name
   exists - the join falls back to the company name - so adding
   'Emirates Building System' to vms.Entity and re-running is enough, with no
   edit to this map.

   Companies in the export with no entity of that name at the time this was
   generated, largest first:
       189  Emirates Building System
        98  Emirates Glass
        48  Emirates Extrusion Factory
        29  White Aluminium Extrusion
        17  Gulf Metal Craft
        16  Lite-Tech Industries
        13  Al Taif Investment
        12  Emirates Extruded Polystyrene
         8  DIP Angola
         2  Mirdif Hills
         2  DI Investment Holding Limited
         1  Palisades
         1  Al Mal Capital
   That is 436 of 725 people. They are kept, with a null
   DiEntityId, and found under "Search all entities" rather than dropped. */

DECLARE @map TABLE (CompanyName NVARCHAR(200), EntityName NVARCHAR(200));

INSERT INTO @map (CompanyName, EntityName) VALUES
(N'Al Mujama Real Estate', N'ALMujama'),
(N'Danah Bay', N'DanahBay'),
(N'Dubai Investment Realestate', N'DIR'),
(N'Dubai Investments Industries', N'DII'),
(N'Dubai Investments PJSC', N'DI'),
(N'Dubai Investments Park', N'DIP'),
(N'Glass LLC', N'GlassLLC'),
(N'Masharie', N'Masharie'),
(N'Mujama', N'ALMujama'),
(N'PID Owners Association Management', N'PIDOA'),
(N'Properties Investment', N'PI'),
(N'TechSource', N'TechSource');

/* ---- 1. people who are new. Matched on email where there is one, because two
        people in this export share a display name and neither shares an email. */

INSERT INTO vms.Person (DisplayName, Title, Email, CompanyName)
SELECT p.DisplayName, NULLIF(p.Title, N''), NULLIF(p.Email, N''), NULLIF(p.CompanyName, N'')
FROM @people p
WHERE NOT EXISTS (
    SELECT 1 FROM vms.Person e
    WHERE (p.Email <> N'' AND e.Email = p.Email)
       OR (p.Email = N'' AND e.Email IS NULL AND e.DisplayName = p.DisplayName));

PRINT CONCAT(N'People inserted: ', @@ROWCOUNT);
GO

/* ---- 2. titles and companies for people already there, since a job changes
        more often than a name does. */

UPDATE e
   SET e.Title       = NULLIF(p.Title, N''),
       e.CompanyName = NULLIF(p.CompanyName, N'')
FROM vms.Person e
JOIN @people p ON p.Email <> N'' AND e.Email = p.Email
WHERE ISNULL(e.Title, N'') <> ISNULL(NULLIF(p.Title, N''), N'')
   OR ISNULL(e.CompanyName, N'') <> ISNULL(NULLIF(p.CompanyName, N''), N'');

PRINT CONCAT(N'People updated: ', @@ROWCOUNT);

/* ---- 3. the entity link, re-resolved for everyone. */

UPDATE p
   SET p.DiEntityId = x.Id
FROM vms.Person p
LEFT JOIN @map m ON m.CompanyName = p.CompanyName
LEFT JOIN vms.Entity x ON x.Name = COALESCE(m.EntityName, p.CompanyName)
WHERE ISNULL(p.DiEntityId, -1) <> ISNULL(x.Id, -1);

PRINT CONCAT(N'Entity links changed: ', @@ROWCOUNT);

SELECT ISNULL(x.Name, N'(no entity)') AS Entity, p.CompanyName, COUNT(*) AS People
FROM vms.Person p
LEFT JOIN vms.Entity x ON x.Id = p.DiEntityId
GROUP BY x.Name, p.CompanyName
ORDER BY CASE WHEN x.Name IS NULL THEN 1 ELSE 0 END, People DESC;
GO
