#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef T5AIRSNAPFRAMEWORK_SWIFT_H
#define T5AIRSNAPFRAMEWORK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#import <T5AirSnapFramework/T5AirSnapFramework.h>

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="T5AirSnapFramework",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Error codes from CaptureStatus
SWIFT_CLASS("_TtC18T5AirSnapFramework14CaptureStatus_")
@interface CaptureStatus_ : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Enum keeps information about image format
SWIFT_CLASS("_TtC18T5AirSnapFramework20FINGER_IMAGE_FORMAT_")
@interface FINGER_IMAGE_FORMAT_ : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Structure keeps information about image data
SWIFT_CLASS("_TtC18T5AirSnapFramework10ImageData_")
@interface ImageData_ : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Holds segmented rectangle and/or image
SWIFT_CLASS("_TtC18T5AirSnapFramework12SgmRectImage")
@interface SgmRectImage : NSObject
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSString;
/// Detect fingers on image during preview and post process segmentation
/// authors:
/// Dmitry Chirkin, Alexey Kuzmichev
/// version:
/// 7.3.0
SWIFT_CLASS("_TtC18T5AirSnapFramework9T5AirSnap")
@interface T5AirSnap : NSObject
/// Retrieves the identifier of your mac device.
///
/// returns:
/// The string with the identifier.
- (NSString * _Nonnull)getDeviceIdentifier SWIFT_WARN_UNUSED_RESULT;
/// Returns SDK version.
///
/// returns:
/// SDK version.
- (NSString * _Nonnull)getVersion SWIFT_WARN_UNUSED_RESULT;
/// Returns the optimal zoom factor for the phone
///
/// returns:
/// zoom factor
- (float)getZoomFactor SWIFT_WARN_UNUSED_RESULT;
/// Returns the optimal exposure compensation for the phone
///
/// returns:
/// exposure compensation
- (float)getExposureCompensation SWIFT_WARN_UNUSED_RESULT;
/// gets current license data
///
/// returns:
/// current license data
- (NSString * _Nonnull)getLicenseData SWIFT_WARN_UNUSED_RESULT;
/// Set license portal url string
/// <ul>
///   <li>
///     parameters:
///   </li>
///   <li>
///     url: (input) URL to license portal. If empty string set then will be used a default path
///   </li>
/// </ul>
- (void)setLicenseURLWithUrl:(uint8_t const * _Nonnull)url;
/// Set outside capture flag
/// \param outsideCapture (input) outside capture flag
///
- (void)setOutsideCaptureFlagWithOutsideCapture:(BOOL)outsideCapture;
/// Set finger image format
/// \param fingerImageFormat (input) finger image format ( the default is WSQ )
///
- (void)setFingerImageFormatWithFingerImageFormat:(int32_t)fingerImageFormat;
/// Set WSQ image formet compression level
/// \param compressionRatio (input) compression ratio ( default value is 10.0)
///
- (void)setWsqCompressionRatioWithCompressionRatio:(float)compressionRatio;
/// Set PNG image formet compression level
/// \param compressionLevel (input) compression level ( default value is 1)
///
- (void)setPngCompressionLevelWithCompressionLevel:(uint8_t)compressionLevel;
/// Set crop parameters
/// \param enabled (input) crop enabled flag.
///
/// \param width (input) crop width (the default width is 512).
///
/// \param height (input) crop height (the default height is 512).
///
/// \param paddingColor (input) padding color (the default color is 255 - white).
///
- (void)setCropParametersWithEnabled:(BOOL)enabled width:(int32_t)width height:(int32_t)height paddingColor:(uint8_t)paddingColor;
/// Set capture metadata.
/// \param metadata (input) capture metadata.
///
- (void)setCaptureMetadataWithMetadata:(uint8_t const * _Nonnull)metadata;
/// Deregister license
///
/// returns:
/// true if success
- (BOOL)deregisterDevice SWIFT_WARN_UNUSED_RESULT;
/// Initialize SDK.
/// \param license (input) the project’s license token.
///
/// \param ret (output) result code of initialization
///
///
/// returns:
/// description of result code.
- (NSString * _Nonnull)initSDKWithLicense:(uint8_t const * _Nonnull)license ret:(int32_t * _Nonnull)ret SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Initialize  NFIQ2 quality assessment
///
/// returns:
/// SE_OK if success and error code otherwise ( -seealso: StandardErrorCodes ).
- (int32_t)initNfiq2 SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Initialize liveness detector
///
/// returns:
/// SE_OK if success and error code otherwise ( -seealso: StandardErrorCodes ).
- (int32_t)initLivenessDetector SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Initialize reverse (nail) detector
///
/// returns:
/// SE_OK if success and error code otherwise ( -seealso: StandardErrorCodes ).
- (int32_t)initReverseDetector SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Initialize thumb  detector
///
/// returns:
/// SE_OK if success and error code otherwise ( -seealso: StandardErrorCodes ).
- (int32_t)initThumbDetector SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
/// Closes work with SDK.
///
/// returns:
/// SE_OK if success and error code otherwise ( -seealso: StandardErrorCodes).
- (int32_t)shutdownSDK SWIFT_WARN_UNUSED_RESULT;
/// Set orientation check flag value.
/// \param orientationCheck (input) orientation check flag value. The default value is true.
///
- (void)setOrientationCheckWithOrientationCheck:(BOOL)orientationCheck;
/// Set operator mode flag value.
/// \param operatorMode (input) operator mode flag value. The default value is false.
///
- (void)setOperatorModeWithOperatorMode:(BOOL)operatorMode;
/// Set liveness check flag value.
/// \param livenessCheck (input) liveness check flag value. The default value is false.
///
- (void)setLivenessCheckWithLivenessCheck:(BOOL)livenessCheck;
/// Set liveness treshold
/// \param livenessThreshold (input) liveness threshold. The default value is 0.5.
///
- (void)setLivenessThresholdWithLivenessThreshold:(float)livenessThreshold;
/// Set fingerprint position code.
/// \param positionCode (input) fingerprint position code ( - seealso: NistPosCode ). The default falue is unknown finger position (POS_CODE_U_FINGER).
///
- (void)setPositionCodeWithPositionCode:(NSInteger)positionCode;
/// Set treshold for finger detector
/// \param detectorThreshold the finger detector treshold from 0.8 to 0.9 The default value is 0.9.
///
///
/// returns:
/// SE_OK if success or SE_WRONG_PARAMETER if detectorThreshold not in range from 0.8 to 0.9
- (int32_t)setDetectorThresholdWithDetectorThreshold:(float)detectorThreshold SWIFT_WARN_UNUSED_RESULT;
/// Set cache directory
/// \param cacheDir cache directory path
///
- (void)setCacheDirWithCacheDir:(NSString * _Nonnull)cacheDir;
/// Set path to models
/// \param modelsDir model directory path
///
- (void)setModelsDirWithModelsDir:(NSString * _Nonnull)modelsDir;
/// Set capture ID.
/// \param captureId (input) capture ID.
///
- (void)setCaptureIdWithCaptureId:(NSString * _Nonnull)captureId;
/// Set device info.
/// \param manufacturer (input) device manufacturer.
///
/// \param model (input) device model.
///
/// \param osVersion (input) device OS version.
///
- (void)setDeviceInfoWithManufacturer:(NSString * _Nonnull)manufacturer model:(NSString * _Nonnull)model osVersion:(NSString * _Nonnull)osVersion;
/// Set save SDK log flag.
/// \param saveSdkLog (input) save SDK log flag.
///
- (void)setSaveSdkLogFlagWithSaveSdkLog:(BOOL)saveSdkLog;
/// Set save frames flag
/// \param saveFrames indicates save or not frames while capture in progress
///
- (void)setSaveFramesFlagWithSaveFrames:(BOOL)saveFrames;
/// Set prop denoise flag.
/// \param propDenoise (input) prop denoise flag.
///
- (void)setPropDenoiseFlagWithPropDenoise:(BOOL)propDenoise;
/// Set capture speed
/// \param captureSpeed (input) capture speed value range : 0.0 - 1.0 where 0.0 - low speed with maximum possible quality and 1.0 - high speed with normal quality
///
- (void)setCaptureSpeedWithCaptureSpeed:(float)captureSpeed;
/// Initialize border parameters
/// \param frameWidth (input) analyzed frame width
///
/// \param frameHeight (input) analyzed frame height
///
/// \param viewWidth (input) view width
///
/// \param viewHeight (input) view width
///
- (void)initBorderWithFrameWidth:(int32_t)frameWidth frameHeight:(int32_t)frameHeight viewWidth:(int32_t)viewWidth viewHeight:(int32_t)viewHeight SWIFT_METHOD_FAMILY(none);
/// Returns border rectangle coordinates
/// \param left (output) left
///
/// \param top (output) top
///
/// \param right (output) right
///
/// \param bottom (output) bottom
///
///
/// returns:
/// SE_OK if success
- (int32_t)getBorderRectangleWithLeft:(int32_t * _Nonnull)left top:(int32_t * _Nonnull)top right:(int32_t * _Nonnull)right bottom:(int32_t * _Nonnull)bottom SWIFT_WARN_UNUSED_RESULT;
/// Analyze preview frame image
/// attention:
/// The function should be called for each frame of the preview until the bestFrameChosen capture status is returned.
/// seealso:
/// CaptureStatus.
/// \param yBuffer (input)  plane #0 of preview frame image;
///
/// \param vuBuffer (input)  plane #1 of preview frame image;
///
/// \param rotationDegrees (input)  frame rotation angle (orientation);
///
/// \param width (input)  width of preview frame image;
///
/// \param height (input)  height of preview frame image;
///
/// \param rects (input/output) array of fingerprint rectangles. In the returned rectangles (SgmRectImage type) of the rectangles list, an array of coordinates ‘coords’ : The element 0 contains the coordinates of the center of the extreme phalanx of the finger; The element 1 contains the coordinates of the center of the flexor fold of the extreme phalanx of the finger; The elements 2 and 3 are not used.
///
/// \param rectsCount (input/output) number of entries in array of fingerprint rectangles. For slaps only : If rectsCount is set to zero then function will search on the slap 4 fingers. If the number of fingers different from 4, You must specify the field ‘pos’ for each element in rects array ( fill array starts from index 0 to rectsCount).
///
///
/// returns:
/// capture status code
- (NSInteger)analyzeImageWithYBuffer:(uint8_t * _Nonnull)yBuffer vuBuffer:(uint8_t * _Nonnull)vuBuffer rotationDegrees:(int32_t)rotationDegrees width:(int32_t)width height:(int32_t)height rects:(NSArray<SgmRectImage *> * _Nonnull)rects rectsCount:(int32_t * _Nonnull)rectsCount SWIFT_WARN_UNUSED_RESULT;
/// Checks reverse hand or  not is present on final frame
/// \param reverseFlag (output) if on frame detected reverse hand it is true.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)checkReverseWithReverseFlag:(BOOL * _Nonnull)reverseFlag SWIFT_WARN_UNUSED_RESULT;
/// Checks left or right thumb is present on final frame
/// \param wrongThumb (output) if we seek left ( right ) thumb and on frame detected left ( right ) it is true.
///
///
/// returns:
/// SE_OK if success and error code otherwise.
- (int32_t)checkThumbWithWrongThumb:(BOOL * _Nonnull)wrongThumb SWIFT_WARN_UNUSED_RESULT;
/// Return result captured frame and segmented fingerprint images.
/// attention:
/// The function should be called on bestFrameChosen capture status.
/// seealso:
/// StandardErrorCodes .
/// \param grayBuffer (output) result captured frame raw image (grayscale);
///
/// \param width (output) width of grayBuffer;
///
/// \param height (output) height of grayBuffer;
///
/// \param rects (output) array of segmented fingerprint images;
///
/// \param rectsCount (output) number of entries in array of segmented fingerprint images;
///
/// \param gender (input)  gender (see {@link Gender});
///
/// \param age (input)  age (0 - unknown; 1 … 99 - age in years);
///
/// \param clean (input) fingerprint clean flag;
///
/// \param livenessScore (output) liveness score (0 … 1.0). It holds  score of liveness, where 0 means fake image of finger.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)segmentFingersWithGrayBuffer:(uint8_t * _Nonnull)grayBuffer width:(int32_t * _Nonnull)width height:(int32_t * _Nonnull)height rects:(NSArray<SgmRectImage *> * _Nonnull)rects rectsCount:(int32_t * _Nonnull)rectsCount gender:(uint8_t)gender age:(uint8_t)age clean:(BOOL)clean livenessScore:(float * _Nonnull)livenessScore SWIFT_WARN_UNUSED_RESULT SWIFT_DEPRECATED_MSG("use getSegmentedFingers instead");
/// Returns result captured frame and segmented fingerprint images.
/// attention:
/// The function should be called on bestFrameChosen capture status.
/// seealso:
/// StandardErrorCodes .
/// \param grayBuffer (output) result captured frame raw image (grayscale);
///
/// \param gender (input)  gender (see {@link Gender});
///
/// \param age (input)  age (0 - unknown; 1 … 99 - age in years);
///
/// \param clean (input) fingerprint clean flag;
///
/// \param rects (output) array of segmented fingerprint images;
///
/// \param rectsCount (output) number of entries in array of segmented fingerprint images;
///
/// \param livenessScore (output) liveness score (0 … 1.0). It holds  score of liveness, where 0 means fake image of finger..
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)getSegmentedFingersWithGrayBuffer:(uint8_t * _Nonnull)grayBuffer gender:(uint8_t)gender age:(uint8_t)age clean:(BOOL)clean rects:(NSArray<SgmRectImage *> * _Nonnull)rects rectsCount:(int32_t * _Nonnull)rectsCount livenessScore:(float * _Nonnull)livenessScore SWIFT_WARN_UNUSED_RESULT;
/// The function takes set of images as input and outputs the Minex template.
/// seealso:
/// StandardErrorCodes .
/// warning:
/// In case of failure the null template will be output.
/// \param rawImages (input)  array of source raw images ( - seealso: RawImage);
///
/// \param numFingers (input)  number of entries in array of source raw images;
///
/// \param minexTemplateType (input)  type of minex template ( - seealso: MinexTemplateType);
///
/// \param templateBuffer (output) memory for the template should be allocated by application (e.g allocateTemplate function);
///
/// \param nistQuality (output) array of NIST quality of images in template (NFIQ);
///
/// \param quality (output) array of quality of images;
///
/// \param minutiaesNumber (output) array of minutiaes number;
///
/// \param tempateSize (output) size of created template in bytes.
///
/// \param maxTemplateSize (input)  maximum size of template. Must be ZERO if unused.
///
/// \param certifiedSensor (input)  true if image taken from scanner that certified by FBI.
///
/// \param sensorId (input)  FBI registration number of scanner.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)createTemplateMinexWithRawImages:(struct RawImage * _Nonnull)rawImages numFingers:(uint32_t)numFingers minexTemplateType:(int32_t)minexTemplateType templateBuffer:(uint8_t * _Nonnull)templateBuffer nistQuality:(uint8_t * _Nonnull)nistQuality quality:(uint8_t * _Nonnull)quality minutiaesNumber:(uint32_t * _Nonnull)minutiaesNumber templateSize:(uint32_t * _Nonnull)templateSize maxTemplateSize:(int32_t)maxTemplateSize certifiedSensor:(BOOL)certifiedSensor sensorId:(uint16_t)sensorId SWIFT_WARN_UNUSED_RESULT;
/// Calculate NIST Finger Image Quality (NFIQ) value.
/// seealso:
/// StandardErrorCodes.
/// warning:
/// In case of failure the 0 quality will be output.
/// \param rawImage (input)  source raw image (grayscale);
///
/// \param width (input)  source image width;
///
/// \param height (input)  source image height;
///
/// \param quality (output) NIST Finger Image Quality (NFIQ) value.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)getNistFingerImageQualityWithRawImage:(uint8_t * _Nonnull)rawImage width:(int32_t)width height:(int32_t)height quality:(uint8_t * _Nonnull)quality SWIFT_WARN_UNUSED_RESULT;
/// Calculate NIST Finger Image Quality (NFIQ2) value.
/// seealso:
/// StandardErrorCodes.
/// warning:
/// In case of failure the 0 quality will be output.
/// \param rawImage (input)  source raw image (grayscale);
///
/// \param width (input)  source image width;
///
/// \param height (input)  source image height;
///
/// \param quality (output) NIST Finger Image Quality (NFIQ2) value.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)getNistFingerImageQuality2WithRawImage:(uint8_t * _Nonnull)rawImage width:(int32_t)width height:(int32_t)height quality:(uint8_t * _Nonnull)quality SWIFT_WARN_UNUSED_RESULT;
/// Calculate  fingerprint  quality  value.
/// seealso:
/// StandardErrorCodes.
/// warning:
/// In case of failure the 0 quality will be output.
/// \param rawImage (input)  source raw image (grayscale);
///
/// \param width (input)  source image width;
///
/// \param height (input)  source image height;
///
/// \param quality (output)  fingerprint quality  value.
///
///
/// returns:
/// SE_OK if success and error code otherwise
- (int32_t)getFingerprintQualityWithRawImage:(uint8_t * _Nonnull)rawImage width:(int32_t)width height:(int32_t)height quality:(uint8_t * _Nonnull)quality SWIFT_WARN_UNUSED_RESULT;
/// Write data functions for the exchange of fingerprint, facial and smt information according to the
/// ANSI / NIST-ITL 1-2011 standard Update: 2015
/// \param is_FBI (input) if 0 then information will be saved in Interpol standard otherwise in FBI standard
///
/// \param demographicsInfo (input) the user defined info as array of pair key/value
/// in current version used interpol v.0500 format
///
/// \param fingers (input) array of fingerprints
///
/// \param faces (input) array of photos
/// If front face present it must be in first element
/// If right profile present it must be in second element
/// If left profile present it must be in third element
/// If angled face present it must be in fourth element
/// If some of them left them corresponded element must be empty
///
/// \param tenprints (input) tenprint images ( 4 + 4 +2 )
///
/// \param nistBuffer (output) result buffer in ANSI/NIST format
///
/// \param length_nistBuffer (output) length of nistBuffer in bytes
///
///
/// returns:
/// SE_OK if success
- (int32_t)saveNistFileWithIs_FBI:(int32_t)is_FBI demographicsInfo:(NSDictionary<NSNumber *, NSString *> * _Nonnull)demographicsInfo fingers:(NSArray<SgmRectImage *> * _Nullable)fingers faces:(NSArray<ImageData_ *> * _Nullable)faces tenprints:(NSArray<SgmRectImage *> * _Nullable)tenprints nistBuffer:(uint8_t * _Nullable)nistBuffer length_nistBuffer:(int32_t * _Nonnull)length_nistBuffer SWIFT_WARN_UNUSED_RESULT;
- (void)toggleTorchOn:(BOOL)on;
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// authors:
/// Dmitry Chirkin, Alexey Kuzmichev
/// version:
/// 1.0.0
/// This stucture holds various type of records for interchange biometric information
SWIFT_CLASS("_TtC18T5AirSnapFramework10T5NistType")
@interface T5NistType : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Transaction information header
SWIFT_CLASS("_TtC18T5AirSnapFramework5Type1")
@interface Type1 : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Photographic body part imagery (including face and SMT) record
SWIFT_CLASS("_TtC18T5AirSnapFramework6Type10")
@interface Type10 : NSObject
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Tenprint  image record
SWIFT_CLASS("_TtC18T5AirSnapFramework6Type14")
@interface Type14 : NSObject
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// User-defined descriptive text record e.g. FBI format or Interpol
SWIFT_CLASS("_TtC18T5AirSnapFramework5Type2")
@interface Type2 : NSObject
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Grayscale fingerprint image with 500 ppi only
SWIFT_CLASS("_TtC18T5AirSnapFramework5Type4")
@interface Type4 : NSObject
/// default constructor
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
